#Requires -Version 5.1

<#
.SYNOPSIS
    Generates a self-contained HTML usage-metrics report from script 03 output.

.DESCRIPTION
    Reads PowerBI_UsageMetrics_All.json (produced by 03-Get-UsageMetricByReport.ps1)
    and generates an interactive HTML report with:
        - KPIs: total views, unique viewers, active vs dormant reports
        - Daily views trend chart (line)
        - Top 15 reports by views (horizontal bar)
        - Access method breakdown (donut)
        - Workspace summary table
        - Full ranked report table
        - Key findings and recommendations

.PARAMETER OutputFolder
    Folder that contains PowerBI_UsageMetrics_All.json.
    Defaults to .\Output

.PARAMETER CustomerName
    Display name shown in the report header.
    Defaults to the folder name.

.PARAMETER ReportPath
    Full path for the generated HTML file.
    Defaults to <OutputFolder>\PowerBI_UsageReport_<CustomerName>.html

.PARAMETER Language
    Report language: 1 = English (default), 2 = Spanish, 3 = Portuguese.

.EXAMPLE
    .\05-Generate-UsageReport.ps1

.EXAMPLE
    .\05-Generate-UsageReport.ps1 -OutputFolder .\Output-AMX -CustomerName "AMX Mexico" -Language 2
#>

[CmdletBinding()]
param (
    [string]$OutputFolder = ".\Output",
    [string]$CustomerName = "",
    [string]$ReportPath   = "",
    [ValidateSet(1,2,3)]
    [int]$Language = 1
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# ── Translations ──────────────────────────────────────────────────────────────
$T = @{
    1 = @{
        htmlLang     = 'en'; dateLocale = 'en-US'
        headerLabel  = 'Power BI Usage Metrics Report'
        headerBy     = 'Generated by Microsoft Copilot'
        headerDate   = 'Period:'
        secKPI       = 'Usage Overview'
        secTrend     = 'Daily Views Trend'
        secTop       = 'Top 15 Reports'
        secWS        = 'Workspace Summary'
        secReports   = 'All Reports — Ranked by Views'
        secFindings  = 'Key Findings &amp; Recommendations'
        themeBtn     = '🔴 Red'
        kTotalViews  = 'Total Views'; kTotalViewsSub = 'in selected period'
        kViewers     = 'Unique Viewers'; kViewersSub  = 'distinct users'
        kShares      = 'Total Shares'; kSharesSub     = 'report shares'
        kActive      = 'Active Reports'; kActiveSub   = 'at least 1 view'
        kDormant     = 'Dormant Reports'; kDormantSub = 'zero views'
        kActivePct   = 'Active Rate'; kActivePctSub  = '% of total reports'
        chartTrend   = 'Views per Day'
        chartTop15   = 'Top 15 Reports by Total Views'
        chartAccess  = 'Access Method'
        tblWSName    = 'Workspace'; tblWSCap = 'Capacity'; tblWSRep = 'Reports'
        tblWSViews   = 'Total Views'; tblWSViewers = 'Viewers'; tblWSActive = 'Active'
        tblWSTopRpt  = 'Top Report'
        tblRank      = '#'; tblReport = 'Report'; tblWS = 'Workspace'
        tblViews     = 'Views'; tblViewers = 'Viewers'; tblShares = 'Shares'
        tblTopPage   = 'Top Page'; tblMethod = 'Access'
        fDormTitle   = 'High Report Dormancy'
        fDormLow     = 'Low Report Dormancy — Good Adoption'
        fTopConc     = 'View Concentration in Top Reports'
        fWebFirst    = 'Primary Access via Power BI Web'
        fMobile      = 'Mobile Access Detected'

        fNoViews      = 'No Usage Data Available'
        secSummary    = 'Usage Summary'
        secPerf       = 'Report Performance'
        chartMethod   = 'Consumption Method'
        chartBrowser  = 'Browser'
        tblPerfH1     = 'First Half'
        tblPerfH2     = 'Second Half'
        tblPerfTrend  = 'Trend'
        perfNoteTitle = 'About Opening Time Metrics'
        perfNoteTxt   = 'Typical opening time (p50), daily performance percentiles (P25/P50/P75), and browser-specific timing metrics are available in the built-in Power BI Usage Metrics report for each workspace. The Engagement Trend column above compares view activity from the first vs. second half of the measurement period as a proxy for report popularity changes over time.'
        secRef        = 'Report Metrics Reference'
        btnAll        = 'All'; btnActive = '&#x25CF; Active'; btnDormant = '&#x25CB; Dormant'
        footerBy      = 'Generated by Microsoft Copilot'
    }
    2 = @{
        htmlLang     = 'es'; dateLocale = 'es-MX'
        headerLabel  = 'Reporte de Métricas de Uso Power BI'
        headerBy     = 'Generado por Microsoft Copilot'
        headerDate   = 'Período:'
        secKPI       = 'Resumen de Uso'
        secTrend     = 'Tendencia Diaria de Vistas'
        secTop       = 'Top 15 Reportes'
        secWS        = 'Resumen por Workspace'
        secReports   = 'Todos los Reportes — Ordenados por Vistas'
        secFindings  = 'Hallazgos Clave y Recomendaciones'
        themeBtn     = '🔴 Rojo'
        kTotalViews  = 'Vistas Totales'; kTotalViewsSub = 'en el período'
        kViewers     = 'Usuarios Únicos'; kViewersSub    = 'usuarios distintos'
        kShares      = 'Compartidos'; kSharesSub         = 'compartidos'
        kActive      = 'Reportes Activos'; kActiveSub    = 'al menos 1 vista'
        kDormant     = 'Reportes Dormidos'; kDormantSub  = 'sin vistas'
        kActivePct   = 'Tasa Activa'; kActivePctSub      = '% del total'
        chartTrend   = 'Vistas por Día'
        chartTop15   = 'Top 15 Reportes por Vistas'
        chartAccess  = 'Método de Acceso'
        tblWSName    = 'Workspace'; tblWSCap = 'Capacidad'; tblWSRep = 'Reportes'
        tblWSViews   = 'Vistas'; tblWSViewers = 'Usuarios'; tblWSActive = 'Activos'
        tblWSTopRpt  = 'Top Reporte'
        tblRank      = '#'; tblReport = 'Reporte'; tblWS = 'Workspace'
        tblViews     = 'Vistas'; tblViewers = 'Usuarios'; tblShares = 'Compartidos'
        tblTopPage   = 'Página Top'; tblMethod = 'Acceso'
        fDormTitle   = 'Alta Tasa de Reportes Inactivos'
        fDormLow     = 'Baja Tasa de Inactividad — Buena Adopción'
        fTopConc     = 'Concentración de Vistas en Top Reportes'
        fWebFirst    = 'Acceso Principal vía Power BI Web'
        fMobile      = 'Acceso desde Móvil Detectado'
        fNoViews      = 'Sin Datos de Uso Disponibles'
        secSummary    = 'Resumen de Uso'
        secPerf       = 'Rendimiento de Reportes'
        chartMethod   = 'Método de Consumo'
        chartBrowser  = 'Navegador'
        tblPerfH1     = 'Primera Mitad'
        tblPerfH2     = 'Segunda Mitad'
        tblPerfTrend  = 'Tendencia'
        perfNoteTitle = 'Sobre los Tiempos de Apertura'
        perfNoteTxt   = 'El tiempo típico de apertura (p50), los percentiles de rendimiento diario (P25/P50/P75) y los tiempos por navegador están disponibles en el reporte de métricas de uso integrado de Power BI de cada workspace. La columna Tendencia compara la actividad de la primera vs. segunda mitad del período como indicador de cambio en popularidad.'
        secRef        = 'Referencia de Métricas del Reporte'
        btnAll        = 'Todos'; btnActive = '&#x25CF; Activos'; btnDormant = '&#x25CB; Inactivos'
        footerBy      = 'Generado por Microsoft Copilot'
    }
    3 = @{
        htmlLang     = 'pt'; dateLocale = 'pt-BR'
        headerLabel  = 'Relatório de Métricas de Uso Power BI'
        headerBy     = 'Gerado por Microsoft Copilot'
        headerDate   = 'Período:'
        secKPI       = 'Resumo de Uso'
        secTrend     = 'Tendência Diária de Visualizações'
        secTop       = 'Top 15 Relatórios'
        secWS        = 'Resumo por Workspace'
        secReports   = 'Todos os Relatórios — Ordenados por Visualizações'
        secFindings  = 'Principais Achados e Recomendações'
        themeBtn     = '🔴 Vermelho'
        kTotalViews  = 'Total de Visualizações'; kTotalViewsSub = 'no período'
        kViewers     = 'Usuários Únicos'; kViewersSub    = 'usuários distintos'
        kShares      = 'Compartilhamentos'; kSharesSub    = 'total'
        kActive      = 'Relatórios Ativos'; kActiveSub   = 'ao menos 1 visualização'
        kDormant     = 'Relatórios Inativos'; kDormantSub = 'sem visualizações'
        kActivePct   = 'Taxa Ativa'; kActivePctSub        = '% do total'
        chartTrend   = 'Visualizações por Dia'
        chartTop15   = 'Top 15 Relatórios por Visualizações'
        chartAccess  = 'Método de Acesso'
        tblWSName    = 'Workspace'; tblWSCap = 'Capacidade'; tblWSRep = 'Relatórios'
        tblWSViews   = 'Visualizações'; tblWSViewers = 'Usuários'; tblWSActive = 'Ativos'
        tblWSTopRpt  = 'Top Relatório'
        tblRank      = '#'; tblReport = 'Relatório'; tblWS = 'Workspace'
        tblViews     = 'Visualizações'; tblViewers = 'Usuários'; tblShares = 'Compartilhados'
        tblTopPage   = 'Página Top'; tblMethod = 'Acesso'
        fDormTitle   = 'Alta Taxa de Relatórios Inativos'
        fDormLow     = 'Baixa Inatividade — Boa Adoção'
        fTopConc     = 'Concentração de Visualizações nos Top Relatórios'
        fWebFirst    = 'Acesso Principal via Power BI Web'
        fMobile      = 'Acesso Mobile Detectado'
        fNoViews      = 'Nenhum Dado de Uso Disponível'
        secSummary    = 'Resumo de Uso'
        secPerf       = 'Desempenho de Relatórios'
        chartMethod   = 'Método de Consumo'
        chartBrowser  = 'Navegador'
        tblPerfH1     = 'Primeira Metade'
        tblPerfH2     = 'Segunda Metade'
        tblPerfTrend  = 'Tendência'
        perfNoteTitle = 'Sobre o Tempo de Abertura'
        perfNoteTxt   = 'O tempo típico de abertura (p50), percentis de desempenho diário (P25/P50/P75) e tempos por navegador estão disponíveis no relatório de métricas de uso integrado do Power BI de cada workspace. A coluna Tendência compara a atividade da primeira vs. segunda metade do período como indicador de mudança na popularidade.'
        secRef        = 'Referência de Métricas do Relatório'
        btnAll        = 'Todos'; btnActive = '&#x25CF; Ativos'; btnDormant = '&#x25CB; Inativos'
        footerBy      = 'Gerado por Microsoft Copilot'
    }
}[$Language]

# ── Load data ─────────────────────────────────────────────────────────────────
$usagePath = Join-Path $OutputFolder "PowerBI_UsageMetrics_All.json"
if (-not (Test-Path $usagePath)) {
    throw "Input file not found: $usagePath`nRun 03-Get-UsageMetricByReport.ps1 first."
}

$usageData = Get-Content $usagePath -Raw | ConvertFrom-Json
if (-not $usageData -or $usageData.Count -eq 0) {
    throw "Input file is empty or invalid."
}

if (-not $CustomerName) {
    $CustomerName = (Split-Path (Resolve-Path $OutputFolder) -Leaf)
}
if (-not $ReportPath) {
    $safe = $CustomerName -replace '[\\/:*?"<>|]', '_'
    $ReportPath = Join-Path $OutputFolder "PowerBI_UsageReport_$safe.html"
}

Write-Host "Loading usage data for: $CustomerName" -ForegroundColor Cyan

# ── Flatten all reports ────────────────────────────────────────────────────────
$allReports = [System.Collections.Generic.List[object]]::new()
foreach ($ws in $usageData) {
    foreach ($rpt in $ws.Reports) {
        $allReports.Add([PSCustomObject]@{
            WorkspaceName         = $ws.WorkspaceName
            CapacityType          = $ws.CapacityType
            WorkspaceId           = $ws.WorkspaceId
            ReportId              = $rpt.ReportId
            ReportName            = $rpt.ReportName
            WebUrl                = if ($rpt.WebUrl) { $rpt.WebUrl } else { '' }
            TotalViews            = [int]$rpt.TotalViews
            TotalUniqueViewers    = [int]$rpt.TotalUniqueViewers
            TotalShares           = [int]$rpt.TotalShares
            RankByTotalViewsInOrg = $rpt.RankByTotalViewsInOrg
            ViewsPerDay           = $rpt.ViewsPerDay
            AccessMethodBreakdown = $rpt.AccessMethodBreakdown
            BrowserBreakdown      = $rpt.BrowserBreakdown
            MostViewedPages       = $rpt.MostViewedPages
        })
    }
}

# ── KPIs ──────────────────────────────────────────────────────────────────────
$totalViews     = [int]($allReports | Measure-Object TotalViews -Sum).Sum
$totalViewers   = [int]($allReports | Where-Object { $_.TotalUniqueViewers -gt 0 } |
                        Measure-Object TotalUniqueViewers -Sum).Sum
$totalShares    = [int]($allReports | Measure-Object TotalShares -Sum).Sum
$activeReports  = ($allReports | Where-Object { $_.TotalViews -gt 0 }).Count
$totalReports   = $allReports.Count
$dormantReports = $totalReports - $activeReports
$activePct      = if ($totalReports -gt 0) { [Math]::Round($activeReports / $totalReports * 100, 1) } else { 0 }

$periodStart = if ($usageData[0].PeriodStartDate) { $usageData[0].PeriodStartDate } else { 'N/A' }
$periodEnd   = if ($usageData[0].PeriodEndDate)   { $usageData[0].PeriodEndDate }   else { 'N/A' }
$periodDays  = if ($usageData[0].PeriodDays)      { $usageData[0].PeriodDays }      else { 0 }

Write-Host "  $totalReports reports | $activeReports active | $totalViews total views" -ForegroundColor Gray

# ── Daily trend ────────────────────────────────────────────────────────────────
$dailyMap = @{}
foreach ($rpt in $allReports) {
    foreach ($day in $rpt.ViewsPerDay) {
        if ($day -and $day.Date) {
            $d = $day.Date
            if ($dailyMap.ContainsKey($d)) { $dailyMap[$d] += [int]$day.Views }
            else { $dailyMap[$d] = [int]$day.Views }
        }
    }
}
$sortedDays  = $dailyMap.Keys | Sort-Object
$trendLabels = if ($sortedDays) { ($sortedDays | ForEach-Object { "`"$_`"" }) -join ',' } else { '' }
$trendData   = if ($sortedDays) { ($sortedDays | ForEach-Object { $dailyMap[$_] }) -join ',' } else { '' }

# ── Top 15 reports ─────────────────────────────────────────────────────────────
$top15 = @($allReports | Sort-Object TotalViews -Descending | Select-Object -First 15)
function EscJs($s) { if ($s) { $s -replace '\\','\\' -replace '"','\"' -replace "`r`n",'\n' -replace "`n",'\n' } else { '' } }
$top15Labels = ($top15 | ForEach-Object { "`"$(EscJs $_.ReportName)`"" }) -join ','
$top15Data   = ($top15 | ForEach-Object { $_.TotalViews }) -join ','
$top15Urls   = ($top15 | ForEach-Object { "`"$(EscJs $_.WebUrl)`"" }) -join ','
$top15WS     = ($top15 | ForEach-Object { "`"$(EscJs $_.WorkspaceName)`"" }) -join ','

# ── Access method breakdown ────────────────────────────────────────────────────
$accessMap = @{}
foreach ($rpt in $allReports) {
    foreach ($m in $rpt.AccessMethodBreakdown) {
        if ($m -and $m.Method) {
            if ($accessMap.ContainsKey($m.Method)) { $accessMap[$m.Method] += [int]$m.Views }
            else { $accessMap[$m.Method] = [int]$m.Views }
        }
    }
}
$accessLabels = if ($accessMap.Count -gt 0) { ($accessMap.Keys | ForEach-Object { "`"$(EscJs $_)`"" }) -join ',' } else { '"No data"' }
$accessData   = if ($accessMap.Count -gt 0) { ($accessMap.Keys | ForEach-Object { $accessMap[$_] }) -join ',' } else { '0' }

# ── Browser breakdown ──────────────────────────────────────────────────────────
$browserMap = @{}
foreach ($rpt in $allReports) {
    foreach ($b in $rpt.BrowserBreakdown) {
        if ($b -and $b.Browser) {
            if ($browserMap.ContainsKey($b.Browser)) { $browserMap[$b.Browser] += [int]$b.Views }
            else { $browserMap[$b.Browser] = [int]$b.Views }
        }
    }
}
$browserLabels = if ($browserMap.Count -gt 0) { ($browserMap.Keys | Sort-Object { -$browserMap[$_] } | ForEach-Object { "`"$(EscJs $_)`"" }) -join ',' } else { '' }
$browserData   = if ($browserMap.Count -gt 0) { ($browserMap.Keys | Sort-Object { -$browserMap[$_] } | ForEach-Object { $browserMap[$_] }) -join ',' } else { '' }

# ── Performance trend table (top active reports, first-half vs second-half) ────
$periodMid = if ($sortedDays -and $sortedDays.Count -gt 1) { $sortedDays[[math]::Floor($sortedDays.Count / 2)] } else { '' }
$perfTableParts = foreach ($rpt in ($allReports | Where-Object { $_.TotalViews -gt 0 } | Sort-Object TotalViews -Descending | Select-Object -First 15)) {
    $firstH = if ($periodMid) { [int](($rpt.ViewsPerDay | Where-Object { $_.Date -lt $periodMid } | Measure-Object Views -Sum).Sum) } else { 0 }
    $secH   = if ($periodMid) { [int](($rpt.ViewsPerDay | Where-Object { $_.Date -ge $periodMid } | Measure-Object Views -Sum).Sum) } else { [int]$rpt.TotalViews }
    $trend  = if   ($firstH -eq 0 -and $secH -eq 0) { 'flat' }
              elseif ($firstH -eq 0)                 { 'up'   }
              elseif ($secH   -eq 0)                 { 'down' }
              elseif ($secH -gt [int]($firstH * 1.1)) { 'up'  }
              elseif ($secH -lt [int]($firstH * 0.9)) { 'down'}
              else                                   { 'flat' }
    $topMethod = if ($rpt.AccessMethodBreakdown -and @($rpt.AccessMethodBreakdown).Count -gt 0) { EscJs $rpt.AccessMethodBreakdown[0].Method } else { '' }
    "{`"name`":`"$(EscJs $rpt.ReportName)`",`"ws`":`"$(EscJs $rpt.WorkspaceName)`",`"url`":`"$(EscJs $rpt.WebUrl)`",`"views`":$($rpt.TotalViews),`"viewers`":$($rpt.TotalUniqueViewers),`"firstH`":$firstH,`"secH`":$secH,`"trend`":`"$trend`",`"method`":`"$topMethod`"}"
}
$perfTableJson = if ($perfTableParts) { $perfTableParts -join ',' } else { '' }

# ── Workspace summary JSON ─────────────────────────────────────────────────────
$wsSummaryParts = foreach ($ws in $usageData) {
    $wsViews   = [int]($ws.Reports | Measure-Object TotalViews -Sum).Sum
    $wsActive  = ($ws.Reports | Where-Object { $_.TotalViews -gt 0 }).Count
    $wsViewers = [int]($ws.Reports | Where-Object { $_.TotalUniqueViewers -gt 0 } |
                       Measure-Object TotalUniqueViewers -Sum).Sum
    $wsTop     = @($ws.Reports | Sort-Object TotalViews -Descending) | Select-Object -First 1
    $topName   = if ($wsTop -and $wsTop.ReportName) { EscJs $wsTop.ReportName } else { '' }
    $topViews  = if ($wsTop) { [int]$wsTop.TotalViews } else { 0 }
    "{`"ws`":`"$(EscJs $ws.WorkspaceName)`",`"cap`":`"$(EscJs $ws.CapacityType)`",`"rCount`":$($ws.ReportCount),`"views`":$wsViews,`"viewers`":$wsViewers,`"active`":$wsActive,`"topRpt`":`"$topName`",`"topViews`":$topViews}"
}
$wsSummaryJson = $wsSummaryParts -join ','

# ── Report detail table JSON ───────────────────────────────────────────────────
$reportTableParts = foreach ($rpt in ($allReports | Sort-Object TotalViews -Descending)) {
    $topPage   = if ($rpt.MostViewedPages -and @($rpt.MostViewedPages).Count -gt 0) { EscJs $rpt.MostViewedPages[0].Page } else { '' }
    $topMethod = if ($rpt.AccessMethodBreakdown -and @($rpt.AccessMethodBreakdown).Count -gt 0) { EscJs $rpt.AccessMethodBreakdown[0].Method } else { '' }
    $rank      = if ($rpt.RankByTotalViewsInOrg) { [int]$rpt.RankByTotalViewsInOrg } else { 9999 }
    "{`"name`":`"$(EscJs $rpt.ReportName)`",`"ws`":`"$(EscJs $rpt.WorkspaceName)`",`"url`":`"$(EscJs $rpt.WebUrl)`",`"views`":$($rpt.TotalViews),`"viewers`":$($rpt.TotalUniqueViewers),`"shares`":$($rpt.TotalShares),`"rank`":$rank,`"topPage`":`"$topPage`",`"method`":`"$topMethod`"}"
}
$reportTableJson = $reportTableParts -join ','

# ── Findings data ─────────────────────────────────────────────────────────────
$dormancyPct = if ($totalReports -gt 0) { [Math]::Round($dormantReports / $totalReports * 100, 0) } else { 0 }
$top5Views   = [int]($top15 | Select-Object -First 5 | Measure-Object TotalViews -Sum).Sum
$top5Pct     = if ($totalViews -gt 0) { [Math]::Round($top5Views / $totalViews * 100, 0) } else { 0 }
$webViews    = if ($accessMap.ContainsKey('Power BI Web')) { $accessMap['Power BI Web'] } else { 0 }
$mobileViews = if ($accessMap.ContainsKey('Power BI Mobile')) { $accessMap['Power BI Mobile'] } else { 0 }
$mobilePct   = if ($totalViews -gt 0) { [Math]::Round($mobileViews / $totalViews * 100, 0) } else { 0 }
$generatedDate = (Get-Date -Format 'MMMM dd, yyyy')
$topWsName   = if ($usageData.Count -gt 0) {
    $usageData | ForEach-Object {
        $v = [int]($_.Reports | Measure-Object TotalViews -Sum).Sum
        [PSCustomObject]@{ Name=$_.WorkspaceName; Views=$v }
    } | Sort-Object Views -Descending | Select-Object -First 1 -ExpandProperty Name
} else { '' }

# ── Findings text (language-aware) ────────────────────────────────────────────
if ($Language -eq 1) {
    $fDormText   = if ($dormancyPct -ge 50) {
        "$dormancyPct% of reports ($dormantReports out of $totalReports) had zero views in the past $periodDays days. Consider archiving or retiring unused content to reduce clutter and maintenance overhead."
    } else {
        "Only $dormancyPct% of reports ($dormantReports out of $totalReports) were inactive. Report adoption is healthy — most published reports are being used."
    }
    $fConcText   = "The top 5 reports account for $top5Pct% of all views. While this shows a clear set of high-value reports, consider promoting other reports to a broader audience."
    $fWebText    = "Power BI Web is the primary access channel. Ensure reports are optimized for browser rendering and that page load times are acceptable."
    $fMobileText = "Mobile access represents $mobilePct% of views. Ensure key reports are optimized with a mobile layout using Power BI Desktop's Phone View."
    $fNoDataText = "No view events were captured in the selected period. Verify that the Power BI Administrator role is assigned and that the Activity Events API is enabled in tenant settings."
} elseif ($Language -eq 2) {
    $fDormText   = if ($dormancyPct -ge 50) {
        "$dormancyPct% de los reportes ($dormantReports de $totalReports) no tuvieron vistas en los últimos $periodDays días. Se recomienda archivar el contenido no utilizado."
    } else {
        "Solo $dormancyPct% de los reportes estuvieron inactivos. La adopción es saludable — la mayoría de los reportes publicados están siendo utilizados."
    }
    $fConcText   = "Los 5 reportes más vistos concentran el $top5Pct% de todas las vistas. Considere promover otros reportes para ampliar el alcance."
    $fWebText    = "Power BI Web es el canal de acceso principal. Optimice los reportes para el navegador y verifique los tiempos de carga."
    $fMobileText = "El acceso móvil representa el $mobilePct% de las vistas. Asegúrese de que los reportes clave tengan un diseño optimizado para teléfono."
    $fNoDataText = "No se capturaron eventos de vista en el período. Verifique el rol de Administrador de Power BI y la configuración de la API de eventos de actividad."
} else {
    $fDormText   = if ($dormancyPct -ge 50) {
        "$dormancyPct% dos relatórios ($dormantReports de $totalReports) não tiveram visualizações nos últimos $periodDays dias. Considere arquivar conteúdo não utilizado."
    } else {
        "Apenas $dormancyPct% dos relatórios estiveram inativos. A adoção está saudável — a maioria dos relatórios publicados está sendo usada."
    }
    $fConcText   = "Os 5 relatórios mais vistos concentram $top5Pct% de todas as visualizações. Considere promover outros relatórios para ampliar o alcance."
    $fWebText    = "Power BI Web é o canal de acesso principal. Otimize os relatórios para o navegador e verifique os tempos de carregamento."
    $fMobileText = "Acesso mobile representa $mobilePct% das visualizações. Certifique-se de que os principais relatórios têm layout otimizado para celular."
    $fNoDataText = "Nenhum evento de visualização foi capturado no período. Verifique a função de Administrador do Power BI e as configurações da API de eventos de atividade."
}

# ── Optional: Azure Log Analytics query timings ───────────────────────────────
$laTimingJson = ''
$laDailyJson  = ''
$laHasData    = 0

$laAnswer = Read-Host "`nFetch server-side query performance from Azure Log Analytics? (Y/N)"
if ($laAnswer -match '^[Yy]') {
    $laWorkspaceId = (Read-Host "  Log Analytics Workspace ID (GUID)").Trim()
    $laToken = $null

    # Try Az.Accounts module
    if (Get-Command Get-AzAccessToken -ErrorAction SilentlyContinue) {
        try {
            $laToken = (Get-AzAccessToken -ResourceUrl 'https://api.loganalytics.io' -ErrorAction Stop).Token
            Write-Host "  Auth: Az.Accounts OK" -ForegroundColor Green
        } catch { Write-Warning "Az.Accounts failed: $_" }
    }
    # Fallback: az CLI
    if (-not $laToken) {
        try {
            $t = (az account get-access-token --resource 'https://api.loganalytics.io' --query accessToken -o tsv 2>$null)
            if ($t) { $laToken = $t.Trim(); Write-Host "  Auth: az CLI OK" -ForegroundColor Green }
        } catch {}
    }

    if (-not $laToken) {
        Write-Warning "Could not get a Log Analytics token.`n  Install Az.Accounts:  Install-Module Az.Accounts`n  Or install az CLI:     https://aka.ms/installazurecliwindows"
    } else {
        function Invoke-LAQuery {
            param($WsId, $Token, $Kql)
            $body    = [System.Text.Encoding]::UTF8.GetBytes((ConvertTo-Json @{ query = $Kql } -Compress))
            $headers = @{ Authorization = "Bearer $Token"; 'Content-Type' = 'application/json' }
            Invoke-RestMethod -Method POST -Uri "https://api.loganalytics.io/v1/workspaces/$WsId/query" `
                -Headers $headers -Body $body -ErrorAction Stop
        }
        $sd = $periodStart
        $ed = $periodEnd
        $md = if ($periodMid) { $periodMid } else { $periodStart }

        # Per-report: P25/P50/P75 + first-half vs second-half P50
        $kqlReport = "let sd=datetime('$sd');let ed=datetime('$ed');let md=datetime('$md');PowerBIDatasetsWorkspace|where TimeGenerated between(sd..ed)|where OperationName=='AnalysisServices.QueryEnd' and isnotempty(ReportId) and Duration>0|extend h=iff(TimeGenerated<md,1,2)|summarize p25=round(percentile(Duration,25)),p50=round(percentile(Duration,50)),p75=round(percentile(Duration,75)),ph1=round(percentileif(Duration,50,h==1)),ph2=round(percentileif(Duration,50,h==2)),cnt=count() by rid=tostring(ReportId),rname=tostring(ReportName),wsname=tostring(WorkspaceName)|order by cnt desc|limit 50"
        try {
            Write-Host "  Querying per-report timings..." -ForegroundColor Cyan
            $rptRes = Invoke-LAQuery -WsId $laWorkspaceId -Token $laToken -Kql $kqlReport
            $cols   = @($rptRes.tables[0].columns.name)
            $parts  = foreach ($row in $rptRes.tables[0].rows) {
                $o = @{}; for ($i = 0; $i -lt $cols.Count; $i++) { $o[$cols[$i]] = $row[$i] }
                $ph1 = if ($o['ph1']) { [int]$o['ph1'] } else { 0 }
                $ph2 = if ($o['ph2']) { [int]$o['ph2'] } else { 0 }
                "{`"rid`":`"$(EscJs $o['rid'])`",`"rname`":`"$(EscJs $o['rname'])`",`"wsname`":`"$(EscJs $o['wsname'])`",`"p25`":$([int]$o['p25']),`"p50`":$([int]$o['p50']),`"p75`":$([int]$o['p75']),`"ph1`":$ph1,`"ph2`":$ph2,`"cnt`":$([int]$o['cnt'])}"
            }
            $laTimingJson = $parts -join ','
            Write-Host "    $($rptRes.tables[0].rows.Count) reports with timing data" -ForegroundColor Green
        } catch { Write-Warning "Per-report timing query failed: $_" }

        # Daily aggregate P25/P50/P75 across all queries
        $kqlDaily = "let sd=datetime('$sd');let ed=datetime('$ed');PowerBIDatasetsWorkspace|where TimeGenerated between(sd..ed)|where OperationName=='AnalysisServices.QueryEnd' and Duration>0|summarize p25=round(percentile(Duration,25)),p50=round(percentile(Duration,50)),p75=round(percentile(Duration,75)) by d=format_datetime(bin(TimeGenerated,1d),'yyyy-MM-dd')|order by d asc"
        try {
            Write-Host "  Querying daily timings..." -ForegroundColor Cyan
            $dayRes = Invoke-LAQuery -WsId $laWorkspaceId -Token $laToken -Kql $kqlDaily
            $cols   = @($dayRes.tables[0].columns.name)
            $dparts = foreach ($row in $dayRes.tables[0].rows) {
                $o = @{}; for ($i = 0; $i -lt $cols.Count; $i++) { $o[$cols[$i]] = $row[$i] }
                "{`"d`":`"$($o['d'])`",`"p25`":$([int]$o['p25']),`"p50`":$([int]$o['p50']),`"p75`":$([int]$o['p75'])}"
            }
            $laDailyJson = $dparts -join ','
            Write-Host "    $($dayRes.tables[0].rows.Count) days with timing data" -ForegroundColor Green
        } catch { Write-Warning "Daily timing query failed: $_" }

        if ($laTimingJson -or $laDailyJson) { $laHasData = 1 }
    }
}

# ── Build HTML ────────────────────────────────────────────────────────────────
Write-Host "Building HTML report..." -ForegroundColor Cyan

$html = @"
<!DOCTYPE html>
<html lang="$($T.htmlLang)">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>$CustomerName – $($T.headerLabel)</title>
<script>
  (() => {
    const param = new URLSearchParams(window.location.search).get("clawpilotTheme");
    const theme = (param === 'red') ? 'red' : 'blue';
    document.documentElement.setAttribute("data-theme", theme);
  })();
</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.2/dist/chart.umd.min.js"></script>
<style>
:root, html[data-theme="blue"] {
  color-scheme: light;
  --cp-bg: #f7f4ef; --cp-bg-elevated: #fcfbf8; --cp-surface: #ffffff;
  --cp-surface-soft: #f5f5f5; --cp-border: #dedede; --cp-border-strong: #919191;
  --cp-text: #242424; --cp-text-muted: #5c5c5c; --cp-text-soft: #6f6f6f;
  --cp-accent: #0078d4; --cp-accent-hover: #006bb5; --cp-accent-soft: rgba(0,120,212,0.08);
  --cp-accent-fg: #ffffff; --cp-success: #16a34a; --cp-danger: #dc2626;
  --cp-warning: #f59e0b; --cp-link: #0078d4;
  --cp-shadow: 0 2px 12px rgba(0,0,0,0.08); --cp-overlay: rgba(255,255,255,0.8);
}
html[data-theme="red"] {
  color-scheme: light;
  --cp-bg: #f7f4ef; --cp-bg-elevated: #fcfbf8; --cp-surface: #ffffff;
  --cp-surface-soft: #f5f5f5; --cp-border: #dedede; --cp-border-strong: #919191;
  --cp-text: #242424; --cp-text-muted: #5c5c5c; --cp-text-soft: #6f6f6f;
  --cp-accent: #b11f4b; --cp-accent-hover: #9a1a41; --cp-accent-soft: rgba(177,31,75,0.08);
  --cp-accent-fg: #ffffff; --cp-success: #16a34a; --cp-danger: #dc2626;
  --cp-warning: #f59e0b; --cp-link: #b11f4b;
  --cp-shadow: 0 2px 12px rgba(0,0,0,0.08); --cp-overlay: rgba(255,255,255,0.8);
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { background: var(--cp-bg); color: var(--cp-text); font-family: 'Segoe UI', system-ui, sans-serif; font-size: 14px; line-height: 1.5; }

.report-header { background: var(--cp-link); color: #fff; padding: 28px 48px 24px; display: flex; justify-content: space-between; align-items: flex-end; flex-wrap: wrap; gap: 12px; }
.report-header h1 { font-size: 1.6rem; font-weight: 700; letter-spacing: -0.02em; }
.report-header .subtitle { font-size: 0.88rem; opacity: 0.82; margin-top: 4px; }
.report-header .meta { text-align: right; font-size: 0.8rem; opacity: 0.8; }

.container { max-width: 1280px; margin: 0 auto; padding: 28px 24px 64px; }

.section-title { font-size: 1rem; font-weight: 700; color: var(--cp-text); margin: 32px 0 14px; padding-bottom: 8px; border-bottom: 2px solid var(--cp-link); display: flex; align-items: center; gap: 8px; }

.kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 14px; }
.kpi-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; padding: 18px 20px; box-shadow: var(--cp-shadow); }
.kpi-card .label { font-size: 0.74rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--cp-text-muted); margin-bottom: 5px; }
.kpi-card .value { font-size: 2rem; font-weight: 800; color: var(--cp-link); line-height: 1; }
.kpi-card .sub { font-size: 0.78rem; color: var(--cp-text-soft); margin-top: 5px; }
.kpi-card.good  { border-left: 4px solid var(--cp-success); }
.kpi-card.good .value  { color: var(--cp-success); }
.kpi-card.warn  { border-left: 4px solid var(--cp-warning); }
.kpi-card.warn .value  { color: var(--cp-warning); }
.kpi-card.danger { border-left: 4px solid var(--cp-danger); }
.kpi-card.danger .value { color: var(--cp-danger); }

.chart-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 18px; }
.chart-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; padding: 18px 20px 14px; box-shadow: var(--cp-shadow); }
.chart-card h3 { font-size: 0.8rem; font-weight: 600; color: var(--cp-text-muted); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 14px; }
.chart-card canvas { max-height: 280px; }

.table-wrap { overflow-x: auto; border-radius: 12px; border: 1px solid var(--cp-border); box-shadow: var(--cp-shadow); }
table { width: 100%; border-collapse: collapse; background: var(--cp-surface); }
thead th { background: var(--cp-surface-soft); color: var(--cp-text-muted); font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.05em; padding: 10px 14px; text-align: left; border-bottom: 1px solid var(--cp-border); white-space: nowrap; cursor: pointer; user-select: none; }
thead th:hover { color: var(--cp-link); }
thead th.sorted-asc::after  { content: ' ↑'; color: var(--cp-link); }
thead th.sorted-desc::after { content: ' ↓'; color: var(--cp-link); }
tbody tr { border-bottom: 1px solid var(--cp-border); transition: background 0.1s; }
tbody tr:last-child { border-bottom: none; }
tbody tr:hover { background: var(--cp-accent-soft); }
tbody td { padding: 8px 14px; font-size: 0.83rem; vertical-align: middle; }

.badge { display: inline-block; padding: 2px 9px; border-radius: 99px; font-size: 0.7rem; font-weight: 600; }
.badge-fabric  { background: rgba(22,163,74,0.12); color: var(--cp-success); }
.badge-premium { background: var(--cp-accent-soft); color: var(--cp-accent); }
.badge-active  { background: rgba(22,163,74,0.12); color: var(--cp-success); }
.badge-dormant { background: rgba(245,158,11,0.12); color: var(--cp-warning); }

.bar-mini { display: inline-block; height: 6px; border-radius: 3px; min-width: 2px; vertical-align: middle; margin-right: 6px; }

.findings-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 14px; }
.finding-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; padding: 16px 18px; box-shadow: var(--cp-shadow); }
.finding-card .f-icon { font-size: 1.4rem; margin-bottom: 7px; }
.finding-card h4 { font-size: 0.88rem; font-weight: 700; margin-bottom: 5px; }
.finding-card p  { font-size: 0.8rem; color: var(--cp-text-soft); line-height: 1.55; }
.finding-card.rec   { border-left: 3px solid var(--cp-success); }
.finding-card.risk  { border-left: 3px solid var(--cp-warning); }
.finding-card.info  { border-left: 3px solid var(--cp-link); }
.ref-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; box-shadow: var(--cp-shadow); margin-bottom: 18px; }
.ref-card summary { list-style: none; display: flex; align-items: center; justify-content: space-between; padding: 14px 18px; cursor: pointer; font-weight: 700; font-size: 0.9rem; color: var(--cp-text); user-select: none; gap: 12px; }
.ref-card summary::-webkit-details-marker { display: none; }
.ref-card summary:hover { background: var(--cp-surface-soft); border-radius: 12px; }
.ref-card[open] summary { border-bottom: 1px solid var(--cp-border); border-radius: 12px 12px 0 0; }
.ref-arrow { color: var(--cp-link); font-size: 0.7rem; flex-shrink: 0; transition: transform 0.2s; }
.ref-card[open] .ref-arrow { transform: rotate(90deg); }
.ref-body { padding: 12px 18px 16px; }
.ref-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(290px, 1fr)); gap: 0 24px; }
.ref-item { display: flex; gap: 10px; padding: 9px 4px; border-bottom: 1px solid var(--cp-border); }
.ref-item:last-child { border-bottom: none; }
.ref-icon { font-size: 1rem; flex-shrink: 0; margin-top: 2px; line-height: 1.4; }
.ri-label { font-size: 0.82rem; font-weight: 700; color: var(--cp-text); margin-bottom: 2px; }
.ri-desc  { font-size: 0.78rem; color: var(--cp-text-soft); line-height: 1.45; }

.theme-toggle { position: fixed; top: 14px; right: 18px; background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 8px; padding: 5px 10px; cursor: pointer; font-size: 0.78rem; color: var(--cp-text-muted); z-index: 100; box-shadow: var(--cp-shadow); }
.theme-toggle:hover { background: var(--cp-surface-soft); }
.report-footer { text-align: center; padding: 20px; font-size: 0.76rem; color: var(--cp-text-muted); border-top: 1px solid var(--cp-border); margin-top: 40px; }

.search-bar { margin-bottom: 12px; display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.search-bar input { max-width: 400px; flex: 1 1 200px; padding: 7px 12px; border: 1px solid var(--cp-border); border-radius: 8px; font-size: 0.85rem; color: var(--cp-text); background: var(--cp-surface); outline: none; }
.search-bar input:focus { border-color: var(--cp-link); }
.status-btns { display: flex; gap: 6px; flex-wrap: wrap; }
.status-btn { padding: 5px 14px; border: 1px solid var(--cp-border); border-radius: 20px; font-size: 0.78rem; font-weight: 600; cursor: pointer; background: var(--cp-surface); color: var(--cp-text-muted); transition: background 0.15s, color 0.15s, border-color 0.15s; }
.status-btn:hover { border-color: var(--cp-link); color: var(--cp-link); }
.status-btn.sb-active { background: var(--cp-link); color: #fff; border-color: var(--cp-link); }
a.report-link { color: var(--cp-link); text-decoration: none; }
a.report-link:hover { text-decoration: underline; }
.date-slicer { display:flex; align-items:center; gap:8px; margin-bottom:12px; flex-wrap:wrap; padding:10px 14px; background:var(--cp-surface); border:1px solid var(--cp-border); border-radius:10px; box-shadow:var(--cp-shadow); }
.date-slicer label { font-size:0.82rem; color:var(--cp-text-muted); font-weight:600; }
.date-slicer input[type=date] { padding:4px 8px; border:1px solid var(--cp-border); border-radius:6px; font-size:0.82rem; color:var(--cp-text); background:var(--cp-surface); outline:none; cursor:pointer; }
.date-slicer input[type=date]:focus { border-color:var(--cp-link); }
.date-slicer .ds-btn { padding:4px 12px; border:1px solid var(--cp-link); border-radius:6px; font-size:0.82rem; color:var(--cp-link); background:var(--cp-surface); cursor:pointer; }
.date-slicer .ds-btn:hover { background:var(--cp-accent-soft); }
.date-slicer .ds-btn-reset { border-color:var(--cp-border); color:var(--cp-text-muted); }
.date-slicer .ds-info { font-size:0.78rem; color:var(--cp-text-muted); margin-left:4px; }
</style>
</head>
<body>

<button class="theme-toggle" onclick="toggleTheme()">$($T.themeBtn)</button>

<header class="report-header">
  <div>
    <div style="font-size:0.78rem;opacity:0.72;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:4px">$($T.headerLabel)</div>
    <h1>$CustomerName</h1>
    <div class="subtitle">$($T.headerDate) $periodStart &rarr; $periodEnd ($periodDays days)</div>
  </div>
  <div class="meta">
    <div>$generatedDate</div>
    <div style="margin-top:3px">$($T.headerBy)</div>
  </div>
</header>

<div class="container">

  <div class="section-title"><span>�️</span> $($T.secSummary)</div>
  <div class="table-wrap" style="margin-bottom:4px">
    <table id="summaryTable">
      <thead><tr>
        <th onclick="sortTable('summaryTable',0)">$($T.tblWSName)</th>
        <th onclick="sortTable('summaryTable',1)">$($T.tblWSCap)</th>
        <th onclick="sortTable('summaryTable',2)" style="text-align:right">$($T.tblWSRep)</th>
        <th onclick="sortTable('summaryTable',3)" style="text-align:right">$($T.tblWSViews)</th>
        <th onclick="sortTable('summaryTable',4)" style="text-align:right">$($T.tblWSViewers)</th>
        <th onclick="sortTable('summaryTable',5)" style="text-align:right">$($T.tblWSActive)</th>
      </tr></thead>
      <tbody id="summaryTableBody"></tbody>
    </table>
  </div>

  <div class="section-title"><span>�📊</span> $($T.secKPI)</div>
  <div class="kpi-grid" id="kpiGrid"></div>

  <div class="section-title"><span>📈</span> $($T.secTrend)</div>
  <div class="date-slicer" id="dateSlicer">
    <label>Period:</label>
    <input type="date" id="dsFrom" />
    <span style="font-size:0.82rem;color:var(--cp-text-muted)">to</span>
    <input type="date" id="dsTo" />
    <button class="ds-btn" onclick="applyDateSlicer()">Apply</button>
    <button class="ds-btn ds-btn-reset" onclick="resetDateSlicer()">Reset</button>
    <span class="ds-info" id="dsRangeInfo"></span>
  </div>
  <div class="chart-card" style="margin-bottom:18px">
    <h3 id="trendTitle"></h3>
    <canvas id="trendChart" style="max-height:220px"></canvas>
  </div>

  <div class="section-title"><span>🏆</span> $($T.secTop)</div>
  <div class="chart-card" style="margin-bottom:18px">
    <h3>$($T.chartTop15)</h3>
    <canvas id="top15Chart" style="max-height:360px"></canvas>
  </div>

  <div class="section-title"><span>⚡</span> $($T.secPerf)</div>
  <div class="chart-grid" style="margin-bottom:18px">
    <div class="chart-card">
      <h3>$($T.chartMethod)</h3>
      <canvas id="accessChart" style="max-height:260px"></canvas>
    </div>
    <div class="chart-card">
      <h3>$($T.chartBrowser)</h3>
      <canvas id="browserChart" style="max-height:260px"></canvas>
    </div>
  </div>
  <div class="table-wrap" style="margin-bottom:14px">
    <table id="perfTable">
      <thead><tr>
        <th onclick="sortTable('perfTable',0)">$($T.tblReport)</th>
        <th onclick="sortTable('perfTable',1)">$($T.tblWS)</th>
        <th onclick="sortTable('perfTable',2)" style="text-align:right">$($T.tblViews)</th>
        <th onclick="sortTable('perfTable',3)" style="text-align:right">$($T.tblViewers)</th>
        <th onclick="sortTable('perfTable',4)" style="text-align:right">$($T.tblPerfH1)</th>
        <th onclick="sortTable('perfTable',5)" style="text-align:right">$($T.tblPerfH2)</th>
        <th style="text-align:center">$($T.tblPerfTrend)</th>
        <th>$($T.tblMethod)</th>
      </tr></thead>
      <tbody id="perfTableBody"></tbody>
    </table>
  </div>
  <div style="background:var(--cp-surface);border:1px solid var(--cp-border);border-left:3px solid var(--cp-link);border-radius:12px;padding:16px 18px;box-shadow:var(--cp-shadow);margin-bottom:8px">
    <div style="font-size:1.2rem;margin-bottom:6px">ℹ️</div>
    <h4 style="font-size:0.88rem;font-weight:700;margin-bottom:5px">$($T.perfNoteTitle)</h4>
    <p style="font-size:0.8rem;color:var(--cp-text-soft);line-height:1.55">$($T.perfNoteTxt)</p>
  </div>

  <div id="laSection" style="display:none;margin-top:18px">
    <div class="chart-card" style="margin-bottom:18px">
      <h3>Daily Query Performance — P25 / P50 / P75 (ms)</h3>
      <canvas id="dailyPerfChart" style="max-height:220px"></canvas>
    </div>
    <div style="margin-bottom:8px;padding:0 2px">
      <h3 style="font-size:0.95rem;font-weight:700;color:var(--cp-text);margin-bottom:10px">Query Timing per Report (Log Analytics)</h3>
    </div>
    <div class="table-wrap" style="margin-bottom:12px">
      <table id="timingTable">
        <thead><tr>
          <th onclick="sortTable('timingTable',0)">Report</th>
          <th onclick="sortTable('timingTable',1)">Workspace</th>
          <th onclick="sortTable('timingTable',2)" style="text-align:right">Queries</th>
          <th onclick="sortTable('timingTable',3)" style="text-align:right">P25 (ms)</th>
          <th onclick="sortTable('timingTable',4)" style="text-align:right">P50 (ms)</th>
          <th onclick="sortTable('timingTable',5)" style="text-align:right">P75 (ms)</th>
          <th style="text-align:center">Trend</th>
        </tr></thead>
        <tbody id="timingTableBody"></tbody>
      </table>
    </div>
    <div style="background:var(--cp-surface);border:1px solid var(--cp-border);border-left:3px solid var(--cp-border-strong);border-radius:10px;padding:12px 16px;font-size:0.78rem;color:var(--cp-text-soft);margin-bottom:8px">
      Source: Azure Log Analytics <em>PowerBIDatasetsWorkspace</em> — <em>AnalysisServices.QueryEnd</em> events. Values are server-side dataset query durations in milliseconds and do not include network transit or visual rendering time. Trend column compares median (P50) from first half vs. second half of the period (&#x2191; = improved, &#x2193; = degraded).
    </div>
  </div>

  <div class="section-title"><span>🗂️</span> $($T.secWS)</div>
  <div class="table-wrap">
    <table id="wsTable">
      <thead><tr>
        <th onclick="sortTable('wsTable',0)">$($T.tblWSName)</th>
        <th onclick="sortTable('wsTable',1)">$($T.tblWSCap)</th>
        <th onclick="sortTable('wsTable',2)">$($T.tblWSRep)</th>
        <th onclick="sortTable('wsTable',3)">$($T.tblWSViews)</th>
        <th onclick="sortTable('wsTable',4)">$($T.tblWSViewers)</th>
        <th onclick="sortTable('wsTable',5)">$($T.tblWSActive)</th>
        <th>$($T.tblWSTopRpt)</th>
      </tr></thead>
      <tbody id="wsTableBody"></tbody>
    </table>
  </div>

  <div class="section-title"><span>📋</span> $($T.secReports)</div>
  <div class="search-bar">
    <input type="text" id="reportSearch" placeholder="🔍 Filter reports..." oninput="filterReports()" />
    <div class="status-btns">
      <button class="status-btn sb-active" id="sbAll"     onclick="setStatusFilter('all')">$($T.btnAll)</button>
      <button class="status-btn"           id="sbActive"  onclick="setStatusFilter('active')">$($T.btnActive)</button>
      <button class="status-btn"           id="sbDormant" onclick="setStatusFilter('dormant')">$($T.btnDormant)</button>
    </div>
  </div>
  <div class="table-wrap">
    <table id="reportTable">
      <thead><tr>
        <th onclick="sortTable('reportTable',0)">$($T.tblRank)</th>
        <th onclick="sortTable('reportTable',1)">$($T.tblReport)</th>
        <th onclick="sortTable('reportTable',2)">$($T.tblWS)</th>
        <th onclick="sortTable('reportTable',3)">$($T.tblViews)</th>
        <th onclick="sortTable('reportTable',4)">$($T.tblViewers)</th>
        <th onclick="sortTable('reportTable',5)">$($T.tblShares)</th>
        <th>$($T.tblTopPage)</th>
        <th>$($T.tblMethod)</th>
      </tr></thead>
      <tbody id="reportTableBody"></tbody>
    </table>
  </div>

  <div class="section-title"><span>�</span> $($T.secRef)</div>
  <details class="ref-card">
    <summary><span>Power BI Usage Metrics — Available Metrics in the Report List</span><span class="ref-arrow">&#9654;</span></summary>
    <div class="ref-body">
      <div class="ref-grid">
        <div class="ref-item"><div class="ref-icon">📊</div><div><div class="ri-label">Active reports</div><div class="ri-desc">Reports currently being used within the workspace.</div></div></div>
        <div class="ref-item"><div class="ref-icon">👁️</div><div><div class="ri-label">Total views</div><div class="ri-desc">Total number of report opens across all reports.</div></div></div>
        <div class="ref-item"><div class="ref-icon">👤</div><div><div class="ri-label">Total viewers</div><div class="ri-desc">Total number of unique users who accessed reports.</div></div></div>
        <div class="ref-item"><div class="ref-icon">📈</div><div><div class="ri-label">View trend</div><div class="ri-desc">Compares report view activity between the first and second halves of the selected time period to identify usage growth or decline.</div></div></div>
        <div class="ref-item"><div class="ref-icon">📭</div><div><div class="ri-label">Unused reports</div><div class="ri-desc">Number of reports that have not been opened during the selected timeframe.</div></div></div>
        <div class="ref-item"><div class="ref-icon">📋</div><div><div class="ri-label">Report usage table</div><div class="ri-desc">Detailed breakdown showing report contribution to overall usage, including open percentages, user engagement, viewing trends, and active days.</div></div></div>
        <div class="ref-item"><div class="ref-icon">🔗</div><div><div class="ri-label">Distribution method</div><div class="ri-desc">Indicates how users gained access to reports, such as workspace membership, direct sharing, or app installation.</div></div></div>
        <div class="ref-item"><div class="ref-icon">🖥️</div><div><div class="ri-label">Platform slicer</div><div class="ri-desc">Filters usage by access platform, including Power BI Service, Embedded, or mobile devices.</div></div></div>
        <div class="ref-item"><div class="ref-icon">🆔</div><div><div class="ri-label">Unique viewers</div><div class="ri-desc">Counts individual users (based on Microsoft Entra ID) who opened a report at least once and shows report opens by viewer.</div></div></div>
      </div>
    </div>
  </details>

  <div class="section-title"><span>�💡</span> $($T.secFindings)</div>
  <div class="findings-grid" id="findingsGrid"></div>

</div>

<div class="report-footer">
  $CustomerName &nbsp;·&nbsp; $($T.headerLabel) &nbsp;·&nbsp; $generatedDate &nbsp;·&nbsp; $($T.footerBy)
</div>

<script>
// ── EMBEDDED DATA ─────────────────────────────────────────────────────────────
const D = {
  totalViews:     $totalViews,
  totalViewers:   $totalViewers,
  totalShares:    $totalShares,
  activeReports:  $activeReports,
  dormantReports: $dormantReports,
  totalReports:   $totalReports,
  activePct:      $activePct,
  periodDays:     $periodDays,
  trendLabels:    [$trendLabels],
  trendData:      [$trendData],
  top15Labels:    [$top15Labels],
  top15Data:      [$top15Data],
  top15Urls:      [$top15Urls],
  top15WS:        [$top15WS],
  accessLabels:   [$accessLabels],
  accessData:     [$accessData],
  browserLabels:  [$browserLabels],
  browserData:    [$browserData],
  perfData:       [$perfTableJson],
  laHasData:      $laHasData,
  laTimingData:   [$laTimingJson],
  laDailyPerf:    [$laDailyJson],
  wsSummary:      [$wsSummaryJson],
  reports:        [$reportTableJson]
};

const FINDINGS = {
  dormancyPct: $dormancyPct,
  top5Pct:     $top5Pct,
  mobilePct:   $mobilePct,
  dormText:    "$(EscJs $fDormText)",
  concText:    "$(EscJs $fConcText)",
  webText:     "$(EscJs $fWebText)",
  mobileText:  "$(EscJs $fMobileText)",
  noDataText:  "$(EscJs $fNoDataText)"
};

const LABELS = {
  kTotalViews:  "$($T.kTotalViews)",  kTotalViewsSub: "$($T.kTotalViewsSub)",
  kViewers:     "$($T.kViewers)",     kViewersSub:    "$($T.kViewersSub)",
  kShares:      "$($T.kShares)",      kSharesSub:     "$($T.kSharesSub)",
  kActive:      "$($T.kActive)",      kActiveSub:     "$($T.kActiveSub)",
  kDormant:     "$($T.kDormant)",     kDormantSub:    "$($T.kDormantSub)",
  kActivePct:   "$($T.kActivePct)",   kActivePctSub:  "$($T.kActivePctSub)",
  chartTrend:   "$($T.chartTrend)",
  fDormTitle:   "$($T.fDormTitle)",   fDormLow:       "$($T.fDormLow)",
  fTopConc:     "$($T.fTopConc)",     fWebFirst:      "$($T.fWebFirst)",
  fMobile:      "$($T.fMobile)",      fNoViews:       "$($T.fNoViews)",
  btnAll:       "$($T.btnAll)",       btnActive:      "$($T.btnActive)",  btnDormant: "$($T.btnDormant)"
};

// ── THEME ─────────────────────────────────────────────────────────────────────
function toggleTheme() {
  const cur = document.documentElement.getAttribute('data-theme');
  const next = cur === 'red' ? 'blue' : 'red';
  document.documentElement.setAttribute('data-theme', next);
  const btn = document.querySelector('.theme-toggle');
  btn.textContent = next === 'red' ? '$($T.themeBtn)'.replace('🔴','🔵').replace('Red','Blue').replace('Rojo','Azul').replace('Vermelho','Azul') : '$($T.themeBtn)';
}

// ── COLOURS ───────────────────────────────────────────────────────────────────
function accent()   { return getComputedStyle(document.documentElement).getPropertyValue('--cp-link').trim(); }
function success()  { return getComputedStyle(document.documentElement).getPropertyValue('--cp-success').trim(); }
function warning()  { return getComputedStyle(document.documentElement).getPropertyValue('--cp-warning').trim(); }
function accentSoft(){ return getComputedStyle(document.documentElement).getPropertyValue('--cp-accent-soft').trim(); }

// ── KPI GRID ──────────────────────────────────────────────────────────────────
function buildKPIs() {
  const dormClass = D.activePct < 50 ? 'danger' : D.activePct < 75 ? 'warn' : 'good';
  const kpis = [
    { label: LABELS.kTotalViews,  value: D.totalViews.toLocaleString(),   sub: LABELS.kTotalViewsSub,  cls: '' },
    { label: LABELS.kViewers,     value: D.totalViewers.toLocaleString(),  sub: LABELS.kViewersSub,     cls: '' },
    { label: LABELS.kShares,      value: D.totalShares.toLocaleString(),   sub: LABELS.kSharesSub,      cls: '' },
    { label: LABELS.kActive,      value: D.activeReports.toLocaleString(), sub: LABELS.kActiveSub,      cls: 'good' },
    { label: LABELS.kDormant,     value: D.dormantReports.toLocaleString(),sub: LABELS.kDormantSub,     cls: D.dormantReports > 0 ? 'warn' : '' },
    { label: LABELS.kActivePct,   value: D.activePct + '%',                sub: LABELS.kActivePctSub,   cls: dormClass }
  ];
  document.getElementById('kpiGrid').innerHTML = kpis.map(k =>
    '<div class="kpi-card '+k.cls+'"><div class="label">'+k.label+'</div><div class="value">'+k.value+'</div><div class="sub">'+k.sub+'</div></div>'
  ).join('');
}

// ── TREND CHART ───────────────────────────────────────────────────────────────
let trendChartInst = null;
function buildTrend() {
  document.getElementById('trendTitle').textContent = LABELS.chartTrend;
  if (!D.trendLabels.length) return;
  const dsFrom = document.getElementById('dsFrom');
  const dsTo   = document.getElementById('dsTo');
  if (dsFrom && D.trendLabels.length) {
    dsFrom.min   = D.trendLabels[0];
    dsFrom.max   = D.trendLabels[D.trendLabels.length - 1];
    dsFrom.value = D.trendLabels[0];
    dsTo.min     = D.trendLabels[0];
    dsTo.max     = D.trendLabels[D.trendLabels.length - 1];
    dsTo.value   = D.trendLabels[D.trendLabels.length - 1];
    updateDsInfo();
  }
  trendChartInst = new Chart(document.getElementById('trendChart'), {
    type: 'line',
    data: {
      labels: D.trendLabels,
      datasets: [{ label: LABELS.chartTrend, data: D.trendData, borderColor: accent(),
        backgroundColor: 'rgba(0,120,212,0.07)', fill: true, tension: 0.3,
        pointRadius: D.trendLabels.length > 20 ? 2 : 4, pointHoverRadius: 6 }]
    },
    options: {
      responsive: true, maintainAspectRatio: true,
      plugins: { legend: { display: false } },
      scales: {
        x: { ticks: { maxTicksLimit: 10, font: { size: 11 } }, grid: { display: false } },
        y: { beginAtZero: true, ticks: { font: { size: 11 } } }
      }
    }
  });
}

function updateDsInfo() {
  const from = document.getElementById('dsFrom').value;
  const to   = document.getElementById('dsTo').value;
  const el   = document.getElementById('dsRangeInfo');
  if (el && from && to) {
    const days = Math.round((new Date(to) - new Date(from)) / 86400000) + 1;
    el.textContent = days + ' days selected';
  }
}

function applyDateSlicer() {
  updateDsInfo();
  const from = document.getElementById('dsFrom').value;
  const to   = document.getElementById('dsTo').value;
  if (!from || !to || !trendChartInst) return;
  const out = D.trendLabels.reduce((acc, d, i) => {
    if (d >= from && d <= to) { acc.l.push(d); acc.v.push(D.trendData[i]); }
    return acc;
  }, { l: [], v: [] });
  trendChartInst.data.labels = out.l;
  trendChartInst.data.datasets[0].data = out.v;
  trendChartInst.update();
}

function resetDateSlicer() {
  if (!D.trendLabels.length) return;
  document.getElementById('dsFrom').value = D.trendLabels[0];
  document.getElementById('dsTo').value   = D.trendLabels[D.trendLabels.length - 1];
  applyDateSlicer();
}

// ── TOP 15 CHART ──────────────────────────────────────────────────────────────
function buildTop15() {
  if (!D.top15Labels.length) return;
  const maxV = Math.max(...D.top15Data);
  const colors = D.top15Data.map(v => v === maxV ? accent() : accentSoft() || 'rgba(0,120,212,0.35)');
  new Chart(document.getElementById('top15Chart'), {
    type: 'bar',
    data: {
      labels: D.top15Labels,
      datasets: [{ label: 'Views', data: D.top15Data, backgroundColor: colors,
        borderRadius: 4, borderSkipped: false }]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: true,
      plugins: {
        legend: { display: false },
        tooltip: {
          callbacks: {
            afterLabel: (ctx) => D.top15WS[ctx.dataIndex] ? '  ' + D.top15WS[ctx.dataIndex] : ''
          }
        }
      },
      scales: {
        x: { beginAtZero: true, ticks: { font: { size: 11 } } },
        y: { ticks: {
          font: { size: 11 },
          callback: (v, i) => { const l = D.top15Labels[i] || ''; return l.length > 40 ? l.slice(0,38)+'…' : l; }
        }}
      },
      onClick: (evt, elements) => {
        if (elements.length && D.top15Urls[elements[0].index]) {
          window.open(D.top15Urls[elements[0].index], '_blank');
        }
      }
    }
  });
}

// ── ACCESS CHART ──────────────────────────────────────────────────────────────
function buildAccess() {
  if (!D.accessLabels.length || D.totalViews === 0) return;
  const palette = ['#0078d4','#16a34a','#f59e0b','#dc2626','#8b5cf6','#0ea5e9','#ec4899'];
  new Chart(document.getElementById('accessChart'), {
    type: 'doughnut',
    data: {
      labels: D.accessLabels,
      datasets: [{ data: D.accessData, backgroundColor: palette, hoverOffset: 6, borderWidth: 2 }]
    },
    options: {
      responsive: true, maintainAspectRatio: true,
      plugins: { legend: { position: 'bottom', labels: { font: { size: 11 }, boxWidth: 14 } } }
    }
  });
}

// ── WORKSPACE TABLE ────────────────────────────────────────────────────────────
function buildWSTable() {
  const maxViews = Math.max(...D.wsSummary.map(w => w.views), 1);
  const rows = D.wsSummary.map(w => {
    const isFab = w.cap.toLowerCase().includes('fabric');
    const badgeCls = isFab ? 'badge-fabric' : 'badge-premium';
    const barW = Math.round(w.views / maxViews * 100);
    return '<tr>'+
      '<td><strong>'+w.ws+'</strong></td>'+
      '<td><span class="badge '+badgeCls+'">'+(isFab?'Fabric':'Premium')+'</span></td>'+
      '<td>'+w.rCount+'</td>'+
      '<td><span class="bar-mini" style="width:'+barW+'px;background:var(--cp-link)"></span>'+w.views.toLocaleString()+'</td>'+
      '<td>'+w.viewers.toLocaleString()+'</td>'+
      '<td>'+(w.rCount>0?Math.round(w.active/w.rCount*100)+'%':'-')+'</td>'+
      '<td style="max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+w.topRpt+'">'+w.topRpt+'</td>'+
    '</tr>';
  });
  document.getElementById('wsTableBody').innerHTML = rows.join('');
}

// ── REPORT TABLE ──────────────────────────────────────────────────────────────
let allRows = [];
function buildReportTable() {
  const maxViews = Math.max(...D.reports.map(r => r.views), 1);
  allRows = D.reports.map((r, i) => {
    const isActive = r.views > 0;
    const badge = isActive
      ? '<span class="badge badge-active">&#x25CF;</span>'
      : '<span class="badge badge-dormant">&#x25CB;</span>';
    const nameCell = r.url
      ? '<a class="report-link" href="'+r.url+'" target="_blank">'+r.name+'</a>'
      : r.name;
    const barW = Math.round(r.views / maxViews * 80);
    const rankStr = r.rank < 9999 ? '#'+r.rank : '-';
    return '<tr data-search="'+(r.name+' '+r.ws).toLowerCase()+'" data-status="'+(isActive?'active':'dormant')+'">'+ 
      '<td>'+badge+' '+rankStr+'</td>'+
      '<td style="max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+r.name+'">'+nameCell+'</td>'+
      '<td style="max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+r.ws+'</td>'+
      '<td><span class="bar-mini" style="width:'+barW+'px;background:var(--cp-link)"></span>'+r.views.toLocaleString()+'</td>'+
      '<td>'+r.viewers.toLocaleString()+'</td>'+
      '<td>'+r.shares.toLocaleString()+'</td>'+
      '<td style="max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+r.topPage+'">'+(r.topPage||'-')+'</td>'+
      '<td>'+(r.method||'-')+'</td>'+
    '</tr>';
  });
  document.getElementById('reportTableBody').innerHTML = allRows.join('');
}

let statusFilter = 'all';
function setStatusFilter(v) {
  statusFilter = v;
  ['all','active','dormant'].forEach(s => {
    const btn = document.getElementById('sb'+s.charAt(0).toUpperCase()+s.slice(1));
    if (btn) btn.className = 'status-btn' + (s === v ? ' sb-active' : '');
  });
  filterReports();
}
function filterReports() {
  const q = document.getElementById('reportSearch').value.toLowerCase();
  const rows = document.querySelectorAll('#reportTableBody tr');
  rows.forEach(row => {
    const matchText   = row.dataset.search.includes(q);
    const matchStatus = statusFilter === 'all' || row.dataset.status === statusFilter;
    row.style.display = (matchText && matchStatus) ? '' : 'none';
  });
}

// ── FINDINGS ──────────────────────────────────────────────────────────────────
function buildFindings() {
  const findings = [];
  if (D.totalViews === 0) {
    findings.push({ cls:'risk', icon:'⚠️', title: LABELS.fNoViews, text: FINDINGS.noDataText });
  } else {
    const dormCls = FINDINGS.dormancyPct >= 50 ? 'risk' : 'rec';
    const dormTitle = FINDINGS.dormancyPct >= 50 ? LABELS.fDormTitle : LABELS.fDormLow;
    findings.push({ cls: dormCls, icon: FINDINGS.dormancyPct >= 50 ? '📦' : '✅', title: dormTitle, text: FINDINGS.dormText });
    if (FINDINGS.top5Pct > 0)
      findings.push({ cls:'info', icon:'🎯', title: LABELS.fTopConc, text: FINDINGS.concText });
    findings.push({ cls:'info', icon:'🌐', title: LABELS.fWebFirst, text: FINDINGS.webText });
    if (FINDINGS.mobilePct > 0)
      findings.push({ cls:'rec', icon:'📱', title: LABELS.fMobile, text: FINDINGS.mobileText });
  }
  document.getElementById('findingsGrid').innerHTML = findings.map(f =>
    '<div class="finding-card '+f.cls+'"><div class="f-icon">'+f.icon+'</div><h4>'+f.title+'</h4><p>'+f.text+'</p></div>'
  ).join('');
}

// ── TABLE SORT ────────────────────────────────────────────────────────────────
const sortState = {};
function sortTable(tableId, colIdx) {
  const table = document.getElementById(tableId);
  const tbody = table.querySelector('tbody');
  const rows  = Array.from(tbody.querySelectorAll('tr'));
  const key   = tableId + '_' + colIdx;
  const asc   = sortState[key] !== true;
  sortState[key] = asc;
  rows.sort((a, b) => {
    const av = a.cells[colIdx]?.textContent.trim() || '';
    const bv = b.cells[colIdx]?.textContent.trim() || '';
    const an = parseFloat(av.replace(/[^0-9.-]/g, ''));
    const bn = parseFloat(bv.replace(/[^0-9.-]/g, ''));
    if (!isNaN(an) && !isNaN(bn)) return asc ? an - bn : bn - an;
    return asc ? av.localeCompare(bv) : bv.localeCompare(av);
  });
  rows.forEach(r => tbody.appendChild(r));
  table.querySelectorAll('thead th').forEach((th, i) => {
    th.classList.remove('sorted-asc','sorted-desc');
    if (i === colIdx) th.classList.add(asc ? 'sorted-asc' : 'sorted-desc');
  });
}

// ── WORKSPACE SUMMARY TABLE ───────────────────────────────────────────────────
function buildSummaryTable() {
  const sorted = [...D.wsSummary].sort((a,b) => b.views - a.views);
  const maxV   = Math.max(...sorted.map(w => w.views), 1);
  document.getElementById('summaryTableBody').innerHTML = sorted.map(w => {
    const isFab    = w.cap.toLowerCase().includes('fabric');
    const badgeCls = isFab ? 'badge-fabric' : 'badge-premium';
    const capLabel = w.cap || (isFab ? 'Fabric Capacity' : 'Premium Capacity');
    const activeStr = w.rCount > 0 ? Math.round(w.active / w.rCount * 100) + '%' : '—';
    const barW = Math.round(w.views / maxV * 80);
    return '<tr>'+
      '<td><strong>'+w.ws+'</strong></td>'+
      '<td><span class="badge '+badgeCls+'">['+capLabel+']</span></td>'+
      '<td style="text-align:right">'+w.rCount+'</td>'+
      '<td style="text-align:right"><span class="bar-mini" style="width:'+barW+'px;background:var(--cp-link)"></span>'+w.views.toLocaleString()+'</td>'+
      '<td style="text-align:right">'+w.viewers.toLocaleString()+'</td>'+
      '<td style="text-align:right">'+activeStr+'</td>'+
    '</tr>';
  }).join('');
}

// ── DAILY PERFORMANCE CHART (Log Analytics) ───────────────────────────────────
function buildDailyPerfChart() {
  if (!D.laHasData || !D.laDailyPerf || !D.laDailyPerf.length) return;
  document.getElementById('laSection').style.display = 'block';
  const lbls = D.laDailyPerf.map(function(x) { return x.d; });
  const p25  = D.laDailyPerf.map(function(x) { return x.p25; });
  const p50  = D.laDailyPerf.map(function(x) { return x.p50; });
  const p75  = D.laDailyPerf.map(function(x) { return x.p75; });
  new Chart(document.getElementById('dailyPerfChart'), {
    type: 'line',
    data: {
      labels: lbls,
      datasets: [
        { label: 'P75', data: p75, borderColor: 'rgba(245,158,11,0.7)', backgroundColor: 'rgba(245,158,11,0.07)', fill: true, tension: 0.3, pointRadius: 2, borderWidth: 1.5 },
        { label: 'P50', data: p50, borderColor: accent(), backgroundColor: 'rgba(0,120,212,0.09)', fill: true, tension: 0.3, pointRadius: 3, borderWidth: 2 },
        { label: 'P25', data: p25, borderColor: 'rgba(22,163,74,0.7)', backgroundColor: 'rgba(22,163,74,0.07)', fill: true, tension: 0.3, pointRadius: 2, borderWidth: 1.5 }
      ]
    },
    options: {
      responsive: true, maintainAspectRatio: true,
      plugins: { legend: { position: 'top', labels: { font: { size: 11 }, boxWidth: 14 } } },
      scales: {
        x: { ticks: { maxTicksLimit: 10, font: { size: 11 } }, grid: { display: false } },
        y: { beginAtZero: true, ticks: { font: { size: 11 }, callback: function(v) { return v + ' ms'; } } }
      }
    }
  });
}

// ── QUERY TIMING TABLE (Log Analytics) ────────────────────────────────────────
function buildTimingTable() {
  if (!D.laHasData || !D.laTimingData || !D.laTimingData.length) return;
  document.getElementById('laSection').style.display = 'block';
  const maxP75 = Math.max.apply(null, D.laTimingData.map(function(x) { return x.p75; }).concat([1]));
  document.getElementById('timingTableBody').innerHTML = D.laTimingData.map(function(r) {
    const t = (r.ph1 > 0 && r.ph2 > 0)
      ? (r.ph2 > r.ph1 * 1.1 ? 'down' : r.ph2 < r.ph1 * 0.9 ? 'up' : 'flat')
      : 'flat';
    const tIcon  = { up: '&#x2191;', down: '&#x2193;', flat: '&#x2192;' };
    const tStyle = {
      up:   'color:var(--cp-success);font-size:1.1rem;font-weight:700',
      down: 'color:var(--cp-danger);font-size:1.1rem;font-weight:700',
      flat: 'color:var(--cp-text-muted);font-size:1.1rem'
    };
    const barW = Math.round(r.p50 / maxP75 * 80);
    return '<tr>'+
      '<td style="max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+r.rname+'">'+r.rname+'</td>'+
      '<td style="max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+r.wsname+'</td>'+
      '<td style="text-align:right">'+r.cnt.toLocaleString()+'</td>'+
      '<td style="text-align:right;color:var(--cp-success)">'+r.p25.toLocaleString()+'</td>'+
      '<td style="text-align:right"><span class="bar-mini" style="width:'+barW+'px;background:var(--cp-link)"></span>'+r.p50.toLocaleString()+'</td>'+
      '<td style="text-align:right;color:var(--cp-warning)">'+r.p75.toLocaleString()+'</td>'+
      '<td style="text-align:center;'+tStyle[t]+'">'+tIcon[t]+'</td>'+
    '</tr>';
  }).join('');
}

// ── BROWSER CHART ─────────────────────────────────────────────────────────────
function buildBrowser() {
  if (!D.browserLabels || !D.browserLabels.length || D.totalViews === 0) {
    const el = document.getElementById('browserChart');
    if (el) el.closest('.chart-card').style.opacity = '0.4';
    return;
  }
  const palette = ['#0078d4','#16a34a','#f59e0b','#dc2626','#8b5cf6','#0ea5e9','#ec4899','#94a3b8'];
  new Chart(document.getElementById('browserChart'), {
    type: 'doughnut',
    data: {
      labels: D.browserLabels,
      datasets: [{ data: D.browserData, backgroundColor: palette, hoverOffset: 6, borderWidth: 2 }]
    },
    options: {
      responsive: true, maintainAspectRatio: true,
      plugins: { legend: { position: 'bottom', labels: { font: { size: 11 }, boxWidth: 14 } } }
    }
  });
}

// ── PERFORMANCE TREND TABLE ───────────────────────────────────────────────────
function buildPerfTable() {
  const tbody = document.getElementById('perfTableBody');
  if (!D.perfData || !D.perfData.length) {
    tbody.innerHTML = '<tr><td colspan="8" style="text-align:center;color:var(--cp-text-muted);padding:20px">—</td></tr>';
    return;
  }
  const trendIcon = { up: '↑', down: '↓', flat: '→' };
  const trendStyle = {
    up:   'color:var(--cp-success);font-size:1.1rem;font-weight:700',
    down: 'color:var(--cp-danger);font-size:1.1rem;font-weight:700',
    flat: 'color:var(--cp-text-muted);font-size:1.1rem'
  };
  tbody.innerHTML = D.perfData.map(r => {
    const nameCell = r.url
      ? '<a class="report-link" href="'+r.url+'" target="_blank">'+r.name+'</a>'
      : r.name;
    const t = r.trend || 'flat';
    return '<tr>'+
      '<td style="max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+r.name+'">'+nameCell+'</td>'+
      '<td style="max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+r.ws+'</td>'+
      '<td style="text-align:right">'+r.views.toLocaleString()+'</td>'+
      '<td style="text-align:right">'+r.viewers.toLocaleString()+'</td>'+
      '<td style="text-align:right">'+r.firstH.toLocaleString()+'</td>'+
      '<td style="text-align:right">'+r.secH.toLocaleString()+'</td>'+
      '<td style="text-align:center;'+trendStyle[t]+'">'+trendIcon[t]+'</td>'+
      '<td>'+(r.method||'-')+'</td>'+
    '</tr>';
  }).join('');
}

// ── INIT ──────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  buildSummaryTable();
  buildKPIs();
  buildTrend();
  buildTop15();
  buildAccess();
  buildBrowser();
  buildPerfTable();
  if (D.laHasData) { buildDailyPerfChart(); buildTimingTable(); }
  buildWSTable();
  buildReportTable();
  buildFindings();
});
</script>
</body>
</html>
"@

# ── Write file ────────────────────────────────────────────────────────────────
$html | Out-File -LiteralPath $ReportPath -Encoding UTF8
Write-Host ""
Write-Host "Usage report generated: $ReportPath" -ForegroundColor Green
Write-Host ""
Write-Host "  KPIs:" -ForegroundColor Yellow
Write-Host "    Total Views    : $totalViews"    -ForegroundColor White
Write-Host "    Unique Viewers : $totalViewers"  -ForegroundColor White
Write-Host "    Active Reports : $activeReports / $totalReports ($activePct%)" -ForegroundColor White
Write-Host "    Dormant Reports: $dormantReports ($dormancyPct%)" -ForegroundColor White
Write-Host ""

# Open in default browser
try {
    Start-Process $ReportPath
} catch { }
