<#
.SYNOPSIS
    Generates a self-contained HTML executive report from PBI Assessment output files.

.DESCRIPTION
    Reads PowerBI_Workspaces.json and PowerBI_Reports_All_Workspaces.json from a given
    output folder and produces an interactive HTML report with charts, KPIs, workspace
    table, data sources breakdown, and strategic findings.

.PARAMETER OutputFolder
    Path to the folder containing the assessment JSON output files.
    Defaults to .\Output-BRA

.PARAMETER CustomerName
    Display name of the customer. Defaults to folder name.

.PARAMETER ReportPath
    Path for the generated HTML file.
    Defaults to <OutputFolder>\Executive_Report_<CustomerName>.html

.EXAMPLE
    .\Generate-ExecutiveReport.ps1 -OutputFolder .\Output-BRA -CustomerName "Claro Brazil"

.PARAMETER Language
    Report language. 1 = English, 2 = Spanish, 3 = Portuguese (default).

.EXAMPLE
    .\Generate-ExecutiveReport.ps1 -OutputFolder .\Output-AMX -CustomerName "AMX Mexico" -Language 2
#>

[CmdletBinding()]
param (
    [string]$OutputFolder  = ".\Output-BRA",
    [string]$CustomerName  = "America Movil Mexico",
    [string]$ReportPath    = "",
    [ValidateSet(1,2,3)]
    [int]$Language         = 3
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# ── Translations ─────────────────────────────────────────────────────────────
$translations = @{
  1 = @{  # English
    htmlLang         = 'en'
    dateLocale       = 'en-US'
    dateFormat       = 'MMMM dd, yyyy'
    headerLabel      = 'PowerBI P-SKU &#8594; Fabric F-SKU Assessment'
    headerDate       = 'Collection date:'
    headerBy         = 'Generated by Microsoft Copilot'
    secOverview      = 'Overview'
    secFabric        = 'Microsoft Fabric Adoption'
    secCapacity      = 'Capacity Distribution & Connection Mode'
    secDS            = 'Data Sources (Top Data Sources)'
    secWS            = 'Workspaces — Full Detail'
    secFindings      = 'Key Findings & Recommendations'
    themeBtn         = '🔴 Red'
    themeBtnBlue     = '🔵 Blue'
    themeBtnRed      = '🔴 Red'
    fabCapLabel      = 'Fabric Capacity'
    fabOfTotal       = '% of total'
    fabSKULabel      = 'SKU'
    fabCapName       = 'capacity:'
    fabWSLabel       = 'Workspaces on Fabric'
    fabNone          = 'No Fabric workspace identified'
    fabPilot         = 'Early adoption — pilot phase'
    fabExpanding     = 'Adoption expanding'
    fabLSMLabel      = 'Large Semantic Models'
    fabLSMEnabled    = 'enabled'
    fabLSMNone       = 'Not enabled'
    lsmEnabledTxt    = 'workspace(s) with Large Semantic Model enabled'
    lsmDisabledTxt   = 'Not enabled — all workspaces with StorageFormat: Small'
    chartSKU         = 'Workspaces by Capacity SKU'
    chartConn        = 'Import vs DirectQuery / LiveConnect'
    chartCap         = 'Workspaces by Capacity (name)'
    chartDS          = 'Data Source frequency in datasets'
    chartTopWS       = 'Top 10 Workspaces by Reports'
    tblNum           = '#'
    tblWS            = 'Workspace'
    tblType          = 'Type'
    tblCap           = 'Capacity'
    tblSKU           = 'SKU'
    tblReports       = 'Reports'
    tblStorage       = 'Storage'
    kpiWSLabel       = 'Workspaces'
    kpiWSSub         = 'with dedicated capacity'
    kpiRepLabel      = 'Reports'
    kpiRepSub        = 'across all workspaces'
    kpiImpLabel      = 'Import Mode'
    kpiRepWord       = 'reports'
    kpiDQLabel       = 'DirectQuery/Live'
    kpiEmptyLabel    = 'Empty (0 rep.)'
    kpiEmptySub      = '% of workspaces'
    kpiFabLabel      = 'Fabric Capacity'
    kpiFabSub        = 'workspaces on Fabric'
    connImport       = 'Import'
    connDQ           = 'DirectQuery/Live'
    connUnk          = 'Unknown'
    connLabel        = 'Connections'
    footerOn         = 'Generated on'
    fImpHighTitle    = 'Import Mode Dominance'
    fImpHighText     = 'The vast majority of reports use Import Mode — data is copied into Power BI. This is efficient for performance but may increase capacity consumption and create data latency. Consider DirectLake in Fabric for real-time critical data.'
    fDQHighTitle     = 'Significant DirectQuery Usage'
    fDQHighText      = 'With PCTX% in DirectQuery/LiveConnect, the load on data sources is high. Review query performance and consider optimizing with Aggregations or migrating critical datasets to Import Mode in Fabric.'
    fFab0Title       = 'No Fabric Workspaces'
    fFab0Text        = 'The tenant has no workspaces on Microsoft Fabric capacity. Consider evaluating a migration pilot to leverage Lakehouse, DirectLake, Pipelines, and unified OneLake governance.'
    fFabPilotTitle   = 'Fabric Adoption Beginning'
    fFabPilotText    = 'Microsoft Fabric adoption is in a pilot phase. A structured roadmap is recommended to expand usage, especially in the highest-volume and most critical workspaces.'
    fFabGoodTitle    = 'Relevant Fabric Adoption'
    fFabGoodText     = 'The tenant shows consistent Microsoft Fabric adoption. Evaluate opportunities to consolidate more workloads in Fabric to reduce Premium capacity costs and improve data governance.'
    fEmptyTitle      = 'Workspaces Without Reports'
    fEmptyText       = '% of workspaces have no published reports, consuming capacity without generating visible value. An audit to deactivate or consolidate idle workspaces is recommended.'
    fLSMTitle        = 'Large Semantic Models (LSM)'
    fLSMEnabledText  = 'Some workspaces already use Large Semantic Models. Ensure enablement is aligned with the actual need for datasets over 1 GB.'
    fLSMDisabledText = 'No workspace has Large Semantic Models enabled. For datasets over 1 GB on dedicated capacity, enabling LSM can improve performance and scalability.'
    fODBCTitle       = 'Legacy Sources: ODBC / Oracle Identified'
    fODBCText        = 'ODBC and Oracle connections were identified. These connections are difficult to monitor centrally and may represent failure points. Gradual replacement with native connectors or a managed gateway is recommended for better governance.'
    fFileTitle       = 'File & Web API Dependency'
    fFileText        = 'Sources such as File, Folder, and Web are common in this environment. Dependencies on local files and external URLs represent operational risk. Migrating these sources to a Fabric Lakehouse or warehouse increases resilience and governance.'
    fTop3Title       = 'Top 3 Workspaces Concentrate'
    fTop3Of          = '% of Reports'
    fTop3Sum         = 'total REPSX reports. These workspaces are critical and should have priority governance, monitoring, and capacity SLAs.'
    wsAnd            = 'and'
  }
  2 = @{  # Spanish
    htmlLang         = 'es'
    dateLocale       = 'es-ES'
    dateFormat       = "dd 'de' MMMM 'de' yyyy"
    headerLabel      = 'PowerBI P-SKU &#8594; Fabric F-SKU Assessment'
    headerDate       = 'Fecha de recolección:'
    headerBy         = 'Generado por Microsoft Copilot'
    secOverview      = 'Resumen General'
    secFabric        = 'Adopción de Microsoft Fabric'
    secCapacity      = 'Distribución de Capacidades y Modo de Conexión'
    secDS            = 'Fuentes de Datos (Top Data Sources)'
    secWS            = 'Workspaces — Detalle Completo'
    secFindings      = 'Hallazgos Clave y Recomendaciones'
    themeBtn         = '🔴 Rojo'
    themeBtnBlue     = '🔵 Azul'
    themeBtnRed      = '🔴 Rojo'
    fabCapLabel      = 'Capacidad Fabric'
    fabOfTotal       = '% del total'
    fabSKULabel      = 'SKU'
    fabCapName       = 'capacidad:'
    fabWSLabel       = 'Workspaces en Fabric'
    fabNone          = 'Ningún workspace en Fabric identificado'
    fabPilot         = 'Adopción incipiente — fase piloto'
    fabExpanding     = 'Adopción en expansión'
    fabLSMLabel      = 'Large Semantic Models'
    fabLSMEnabled    = 'habilitado(s)'
    fabLSMNone       = 'No habilitado'
    lsmEnabledTxt    = 'workspace(s) con Large Semantic Model habilitado'
    lsmDisabledTxt   = 'No habilitado — todos los workspaces con StorageFormat: Small'
    chartSKU         = 'Workspaces por SKU de Capacidad'
    chartConn        = 'Import vs DirectQuery / LiveConnect'
    chartCap         = 'Workspaces por Capacidad (nombre)'
    chartDS          = 'Frecuencia de Data Sources en datasets'
    chartTopWS       = 'Top 10 Workspaces por Reportes'
    tblNum           = '#'
    tblWS            = 'Workspace'
    tblType          = 'Tipo'
    tblCap           = 'Capacidad'
    tblSKU           = 'SKU'
    tblReports       = 'Reportes'
    tblStorage       = 'Almacenamiento'
    kpiWSLabel       = 'Workspaces'
    kpiWSSub         = 'con capacidad dedicada'
    kpiRepLabel      = 'Reportes'
    kpiRepSub        = 'en todos los workspaces'
    kpiImpLabel      = 'Import Mode'
    kpiRepWord       = 'reportes'
    kpiDQLabel       = 'DirectQuery/Live'
    kpiEmptyLabel    = 'Vacíos (0 rep.)'
    kpiEmptySub      = '% de los workspaces'
    kpiFabLabel      = 'Fabric Capacity'
    kpiFabSub        = 'workspaces en Fabric'
    connImport       = 'Import'
    connDQ           = 'DirectQuery/Live'
    connUnk          = 'Desconocido'
    connLabel        = 'Conexiones'
    footerOn         = 'Generado el'
    fImpHighTitle    = 'Predominio del Import Mode'
    fImpHighText     = 'La gran mayoría de los reportes usa Import Mode — los datos se copian en Power BI. Es eficiente en rendimiento, pero puede elevar el consumo de capacidad y generar latencia de datos. Considere DirectLake en Fabric para datos críticos en tiempo real.'
    fDQHighTitle     = 'Uso Significativo de DirectQuery'
    fDQHighText      = 'Con PCTX% en DirectQuery/LiveConnect, la carga sobre las fuentes de datos es alta. Verifique el rendimiento de las consultas y considere optimizar con Aggregations o migrar datasets críticos a Import Mode en Fabric.'
    fFab0Title       = 'Ningún Workspace en Fabric'
    fFab0Text        = 'El tenant no tiene workspaces en capacidad Microsoft Fabric. Se recomienda evaluar un piloto de migración para aprovechar Lakehouse, DirectLake, Pipelines y la gobernanza unificada de OneLake.'
    fFabPilotTitle   = 'Inicio de Adopción de Fabric'
    fFabPilotText    = 'La adopción de Microsoft Fabric está en fase piloto. Se recomienda un roadmap estructurado para ampliar el uso, especialmente en los workspaces de mayor volumen y criticidad.'
    fFabGoodTitle    = 'Adopción Relevante de Fabric'
    fFabGoodText     = 'El tenant muestra una adopción consistente de Microsoft Fabric. Evalúe oportunidades de consolidar más cargas de trabajo en Fabric para reducir costos de capacidad Premium y mejorar la gobernanza de datos.'
    fEmptyTitle      = 'Workspaces Sin Reportes'
    fEmptyText       = '% de los workspaces no tienen reportes publicados, consumiendo capacidad sin generar valor visible. Se recomienda una auditoría para desactivar o consolidar workspaces ociosos.'
    fLSMTitle        = 'Large Semantic Models (LSM)'
    fLSMEnabledText  = 'Algunos workspaces ya utilizan Large Semantic Models. Asegúrese de que la habilitación esté alineada con la necesidad real de datasets superiores a 1 GB.'
    fLSMDisabledText = 'Ningún workspace tiene Large Semantic Models habilitado. Para datasets superiores a 1 GB en capacidad dedicada, habilitarlo puede mejorar rendimiento y escalabilidad.'
    fODBCTitle       = 'Fuentes Legadas: ODBC / Oracle Identificadas'
    fODBCText        = 'Se identificaron conexiones ODBC y Oracle. Estas conexiones son difíciles de monitorear centralmente y pueden representar puntos de fallo. Se recomienda reemplazarlas gradualmente por conectores nativos o gateway administrado.'
    fFileTitle       = 'Dependencia de Archivos y APIs Web'
    fFileText        = 'Fuentes como File, Folder y Web son comunes en este entorno. La dependencia de archivos locales y URLs externas representa riesgo operacional. Migrar estas fuentes a un Lakehouse o warehouse en Fabric aumenta la resiliencia y gobernanza.'
    fTop3Title       = 'Top 3 Workspaces Concentran'
    fTop3Of          = '% de los Reportes'
    fTop3Sum         = 'REPSX reportes en total. Estos workspaces son críticos y deben tener gobernanza, monitoreo y SLAs de capacidad prioritarios.'
    wsAnd            = 'y'
  }
  3 = @{  # Portuguese
    htmlLang         = 'pt-BR'
    dateLocale       = 'pt-BR'
    dateFormat       = "dd 'de' MMMM 'de' yyyy"
    headerLabel      = 'PowerBI P-SKU &#8594; Fabric F-SKU Assessment'
    headerDate       = 'Data de coleta:'
    headerBy         = 'Gerado por Microsoft Copilot'
    secOverview      = 'Visão Geral'
    secFabric        = 'Adoção do Microsoft Fabric'
    secCapacity      = 'Distribuição de Capacidades e Modo de Conexão'
    secDS            = 'Fontes de Dados (Top Data Sources)'
    secWS            = 'Workspaces — Detalhamento Completo'
    secFindings      = 'Principais Achados e Recomendações'
    themeBtn         = '🔴 Vermelho'
    themeBtnBlue     = '🔵 Azul'
    themeBtnRed      = '🔴 Vermelho'
    fabCapLabel      = 'Capacidade Fabric'
    fabOfTotal       = '% do total'
    fabSKULabel      = 'SKU'
    fabCapName       = 'capacidade:'
    fabWSLabel       = 'Workspaces em Fabric'
    fabNone          = 'Nenhum workspace em Fabric identificado'
    fabPilot         = 'Adoção incipiente — fase piloto'
    fabExpanding     = 'Adoção em expansão'
    fabLSMLabel      = 'Large Semantic Models'
    fabLSMEnabled    = 'habilitado(s)'
    fabLSMNone       = 'Não habilitado'
    lsmEnabledTxt    = 'workspace(s) com Large Semantic Model habilitado'
    lsmDisabledTxt   = 'Não habilitado — todos os workspaces com StorageFormat: Small'
    chartSKU         = 'Workspaces por SKU de Capacidade'
    chartConn        = 'Import vs DirectQuery / LiveConnect'
    chartCap         = 'Workspaces por Capacidade (nome)'
    chartDS          = 'Frequência de Data Sources nos datasets'
    chartTopWS       = 'Top 10 Workspaces por Relatórios'
    tblNum           = '#'
    tblWS            = 'Workspace'
    tblType          = 'Tipo'
    tblCap           = 'Capacidade'
    tblSKU           = 'SKU'
    tblReports       = 'Relatórios'
    tblStorage       = 'Storage'
    kpiWSLabel       = 'Workspaces'
    kpiWSSub         = 'com capacidade dedicada'
    kpiRepLabel      = 'Relatórios'
    kpiRepSub        = 'em todos os workspaces'
    kpiImpLabel      = 'Import Mode'
    kpiRepWord       = 'relatórios'
    kpiDQLabel       = 'DirectQuery/Live'
    kpiEmptyLabel    = 'Vazios (0 rel.)'
    kpiEmptySub      = '% dos workspaces'
    kpiFabLabel      = 'Fabric Capacity'
    kpiFabSub        = 'workspaces em Fabric'
    connImport       = 'Import'
    connDQ           = 'DirectQuery/Live'
    connUnk          = 'Unknown'
    connLabel        = 'Conexões'
    footerOn         = 'Gerado em'
    fImpHighTitle    = 'Dominância do Import Mode'
    fImpHighText     = 'A grande maioria dos relatórios usa Import Mode — os dados são copiados para o Power BI. É eficiente para performance, mas pode elevar consumo de capacidade e criar latência de dados. Considere DirectLake no Fabric para dados críticos em tempo real.'
    fDQHighTitle     = 'Uso Significativo de DirectQuery'
    fDQHighText      = 'Com PCTX% em DirectQuery/LiveConnect, a carga sobre as fontes de dados é alta. Verifique o desempenho das queries e considere otimizar com Aggregations ou migrar datasets críticos para Import Mode no Fabric.'
    fFab0Title       = 'Nenhum Workspace em Fabric'
    fFab0Text        = 'O tenant não possui workspaces na capacidade Microsoft Fabric. Recomenda-se avaliar um piloto de migração para aproveitar recursos como Lakehouse, DirectLake, Pipelines e governança unificada do OneLake.'
    fFabPilotTitle   = 'Início da Adoção do Fabric'
    fFabPilotText    = 'A adoção do Microsoft Fabric está em fase piloto. Recomenda-se um roadmap estruturado para expandir o uso, especialmente nos workspaces de maior volume e criticidade.'
    fFabGoodTitle    = 'Adoção Relevante do Fabric'
    fFabGoodText     = 'O tenant demonstra adoção consistente do Microsoft Fabric. Avalie oportunidades de consolidar mais cargas de trabalho no Fabric para reduzir custos de capacidade Premium e melhorar a governança de dados.'
    fEmptyTitle      = 'Workspaces Sem Relatórios'
    fEmptyText       = '% dos workspaces não possuem relatórios publicados, consumindo capacidade sem gerar valor visível. Recomenda-se uma auditoria para desativar ou consolidar workspaces ociosos.'
    fLSMTitle        = 'Large Semantic Models (LSM)'
    fLSMEnabledText  = 'Alguns workspaces já utilizam Large Semantic Models. Garanta que a habilitação está alinhada com a necessidade real de datasets acima de 1 GB.'
    fLSMDisabledText = 'Nenhum workspace tem Large Semantic Models habilitado. Para datasets acima de 1 GB em capacidade dedicada, habilitar LSM pode melhorar performance e escalabilidade.'
    fODBCTitle       = 'Fontes Legadas: ODBC / Oracle Identificadas'
    fODBCText        = 'Conexões via ODBC e Oracle foram identificadas. Essas conexões são difíceis de monitorar centralmente e podem representar pontos de falha. Recomenda-se substituição gradual por conectores nativos ou gateway gerenciado para melhor governança.'
    fFileTitle       = 'Dependência de Arquivos e Web APIs'
    fFileText        = 'Fontes como File, Folder e Web são comuns no ambiente. Dependências de arquivos locais e URLs externas representam risco operacional. Migrar essas fontes para um Lakehouse ou warehouse no Fabric aumenta a resiliência e a governança.'
    fTop3Title       = 'Top 3 Workspaces Concentram'
    fTop3Of          = '% dos Relatórios'
    fTop3Sum         = 'REPSX relatórios. Esses workspaces são críticos e devem ter governança, monitoramento e SLAs de capacidade prioritários.'
    wsAnd            = 'e'
  }
}
$T = $translations[$Language]

# ── 1. Resolve paths ─────────────────────────────────────────────────────────
$OutputFolder = Resolve-Path $OutputFolder -ErrorAction Stop

if (-not $CustomerName) {
    $CustomerName = Split-Path $OutputFolder -Leaf
}
if (-not $ReportPath) {
    $safeName = $CustomerName -replace '[\\/:*?"<>| ]', '_'
    $ReportPath = Join-Path $OutputFolder "Executive_Report_$safeName.html"
}

$wsFile  = Join-Path $OutputFolder "PowerBI_Workspaces.json"
$allFile = Join-Path $OutputFolder "PowerBI_Reports_All_Workspaces.json"

if (-not (Test-Path $wsFile))  { throw "File not found: $wsFile" }
if (-not (Test-Path $allFile)) { throw "File not found: $allFile" }

Write-Host ""
Write-Host "Generating executive report for: $CustomerName" -ForegroundColor Cyan
Write-Host "Input folder : $OutputFolder" -ForegroundColor Gray

# ── 2. Parse data ────────────────────────────────────────────────────────────
$ws         = Get-Content $wsFile  -Raw | ConvertFrom-Json
$allData    = Get-Content $allFile -Raw | ConvertFrom-Json
$allReports = @($allData | ForEach-Object { $_.Reports } | Where-Object { $_ -ne $null })
$allDS      = @($allReports | ForEach-Object { $_.DataSources } | Where-Object { $_ -ne $null })

# ── KPIs ─────────────────────────────────────────────────────────────────────
$totalWS      = $ws.Count
$fabricWS     = ($ws | Where-Object { $_.CapacityType -eq 'Fabric Capacity' }).Count
$premiumWS    = ($ws | Where-Object { $_.CapacityType -eq 'PBI Premium Capacity' }).Count
$emptyWS      = ($ws | Where-Object { $_.ReportCount -eq 0 }).Count
$totalReports = $allReports.Count
$importR      = ($allReports | Where-Object { $_.ConnectionMode -eq 'Import' }).Count
$dqR          = ($allReports | Where-Object { $_.ConnectionMode -like 'DirectQuery*' -or $_.ConnectionMode -like 'Direct*' }).Count
$unkR         = ($allReports | Where-Object { $_.ConnectionMode -eq 'Unknown' }).Count

$importPct = if ($totalReports -gt 0) { [math]::Round($importR / $totalReports * 100, 1) } else { 0 }
$dqPct     = if ($totalReports -gt 0) { [math]::Round($dqR     / $totalReports * 100, 1) } else { 0 }

# ── SKU breakdown ─────────────────────────────────────────────────────────────
$skuGroups = $ws | Group-Object CapacitySku | Sort-Object Count -Descending
$skuLabels = ($skuGroups | ForEach-Object { "'$($_.Name) ($($_.Count))'" }) -join ','
$skuData   = ($skuGroups | ForEach-Object { $_.Count }) -join ','
$skuNames  = ($skuGroups | ForEach-Object { "'$($_.Name)'" }) -join ','

# ── Capacity name breakdown ───────────────────────────────────────────────────
$capGroups  = $ws | Group-Object CapacityName | Sort-Object Count -Descending | Select-Object -First 8
$capLabels  = ($capGroups | ForEach-Object { $n = $_.Name; if ($n.Length -gt 22) { $n = $n.Substring(0,20)+'…' }; "'$n'" }) -join ','
$capData    = ($capGroups | ForEach-Object { $_.Count }) -join ','

# ── Top data sources ─────────────────────────────────────────────────────────
$dsGroups = $allDS | Where-Object { $_.datasourceName } | Group-Object datasourceName |
            Sort-Object Count -Descending | Select-Object -First 10
$dsLabels = ($dsGroups | ForEach-Object { "'$($_.Name)'" }) -join ','
$dsData   = ($dsGroups | ForEach-Object { $_.Count }) -join ','

# ── Top 10 workspaces by report count ────────────────────────────────────────
$top10       = $ws | Sort-Object ReportCount -Descending | Select-Object -First 10
$top10Labels = ($top10 | ForEach-Object { $n = $_.Name; if ($n.Length -gt 28) { $n = $n.Substring(0,26)+'…' }; "'$n'" }) -join ','
$top10Data   = ($top10 | ForEach-Object { $_.ReportCount }) -join ','
$top10Colors = ($top10 | ForEach-Object { if ($_.CapacityType -eq 'Fabric Capacity') { "'#16a34a'" } else { "'#b11f4b'" } }) -join ','

# ── Workspace table JSON ─────────────────────────────────────────────────────
$wsSorted = $ws | Sort-Object ReportCount -Descending
$wsJsonRows = ($wsSorted | ForEach-Object {
    $n   = $_.Name    -replace "'", "\'"
    $cap = if ($_.CapacityName) { $_.CapacityName } else { 'Unknown' }
    $cap = $cap -replace "'", "\'"
    $sf  = if ($_.DefaultDatasetStorageFormat) { $_.DefaultDatasetStorageFormat } else { 'Small' }
    "{ name:'$n', cap:'$cap', sku:'$($_.CapacitySku)', type:'$($_.CapacityType)', reports:$($_.ReportCount), storage:'$sf' }"
}) -join (",`n    ")

# ── Fabric workspace names ────────────────────────────────────────────────────
$fabricNames = ($ws | Where-Object { $_.CapacityType -eq 'Fabric Capacity' } | ForEach-Object { $_.Name }) -join ' &nbsp;·&nbsp; '
if (-not $fabricNames) { $fabricNames = 'Nenhum' }
$fabricSku  = ($ws | Where-Object { $_.CapacityType -eq 'Fabric Capacity' } | Select-Object -First 1 -ExpandProperty CapacitySku)
if (-not $fabricSku) { $fabricSku = 'N/A' }
$fabricCap  = ($ws | Where-Object { $_.CapacityType -eq 'Fabric Capacity' } | Select-Object -First 1 -ExpandProperty CapacityName)
if (-not $fabricCap) { $fabricCap = 'N/A' }

# ── LSM check ────────────────────────────────────────────────────────────────
$lsmEnabled = ($ws | Where-Object { $_.DefaultDatasetStorageFormat -eq 'Large' }).Count
$lsmText    = if ($lsmEnabled -gt 0) { "$lsmEnabled $($T.lsmEnabledTxt)" } else { $T.lsmDisabledTxt }

$reportDate = (Get-Date).ToString($T.dateFormat, [System.Globalization.CultureInfo]::GetCultureInfo($T.dateLocale))

Write-Host "  Language    : $($T.htmlLang)" -ForegroundColor Gray
Write-Host "  Workspaces  : $totalWS (Fabric: $fabricWS, Premium: $premiumWS)" -ForegroundColor Gray
Write-Host "  Reports     : $totalReports (Import: $importPct%, DQ: $dqPct%)" -ForegroundColor Gray

# ── 3. Generate HTML ─────────────────────────────────────────────────────────
$html = @"
<!DOCTYPE html>
<html lang="$($T.htmlLang)">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>$CustomerName – Power BI Assessment | Executive Report</title>
<script>
  (() => {
    const param = new URLSearchParams(window.location.search).get("clawpilotTheme");
    const theme = (param === 'red') ? 'red' : 'blue';
    document.documentElement.setAttribute("data-theme", theme);
  })();
</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.2/dist/chart.umd.min.js"></script>
<style>
:root, html[data-theme="blue"] {
  color-scheme: light;
  --cp-bg: #f7f4ef; --cp-bg-elevated: #fcfbf8; --cp-surface: #ffffff;
  --cp-surface-soft: #f5f5f5; --cp-border: #dedede; --cp-border-strong: #919191;
  --cp-text: #242424; --cp-text-muted: #5c5c5c; --cp-text-soft: #6f6f6f;
  --cp-accent: #0078d4; --cp-accent-hover: #006bb5; --cp-accent-soft: rgba(0,120,212,0.08);
  --cp-accent-fg: #ffffff; --cp-success: #16a34a; --cp-danger: #dc2626;
  --cp-warning: #f59e0b; --cp-link: #0078d4;
  --cp-shadow: 0 18px 48px rgba(0,0,0,0.12); --cp-overlay: rgba(255,255,255,0.8);
  --cp-panel: rgba(255,255,255,0.86); --cp-panel-strong: rgba(255,255,255,0.96);
  --cp-sheen: rgba(255,255,255,0.55); --cp-highlight: rgba(0,120,212,0.12);
}
html[data-theme="red"] {
  color-scheme: light;
  --cp-bg: #f7f4ef; --cp-bg-elevated: #fcfbf8; --cp-surface: #ffffff;
  --cp-surface-soft: #f5f5f5; --cp-border: #dedede; --cp-border-strong: #919191;
  --cp-text: #242424; --cp-text-muted: #5c5c5c; --cp-text-soft: #6f6f6f;
  --cp-accent: #b11f4b; --cp-accent-hover: #9a1a41; --cp-accent-soft: rgba(177,31,75,0.08);
  --cp-accent-fg: #ffffff; --cp-success: #16a34a; --cp-danger: #dc2626;
  --cp-warning: #f59e0b; --cp-link: #b11f4b;
  --cp-shadow: 0 18px 48px rgba(0,0,0,0.12); --cp-overlay: rgba(255,255,255,0.8);
  --cp-panel: rgba(255,255,255,0.86); --cp-panel-strong: rgba(255,255,255,0.96);
  --cp-sheen: rgba(255,255,255,0.55); --cp-highlight: rgba(177,31,75,0.12);
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { background: var(--cp-bg); color: var(--cp-text); font-family: 'Segoe UI', system-ui, sans-serif; font-size: 14px; line-height: 1.5; }

.report-header { background: var(--cp-link); color: #ffffff; padding: 32px 48px 28px; display: flex; justify-content: space-between; align-items: flex-end; flex-wrap: wrap; gap: 12px; }
.report-header h1 { font-size: 1.75rem; font-weight: 700; letter-spacing: -0.02em; }
.report-header .subtitle { font-size: 0.95rem; opacity: 0.85; margin-top: 4px; }
.report-header .meta { text-align: right; font-size: 0.82rem; opacity: 0.8; }

.container { max-width: 1280px; margin: 0 auto; padding: 32px 24px 64px; }

.section-title { font-size: 1.05rem; font-weight: 700; color: var(--cp-text); margin: 36px 0 16px; padding-bottom: 8px; border-bottom: 2px solid var(--cp-link); display: flex; align-items: center; gap: 8px; }

.kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 16px; }
.kpi-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; padding: 20px 24px; box-shadow: var(--cp-shadow); transition: transform 0.15s; }
.kpi-card:hover { transform: translateY(-2px); }
.kpi-card .label { font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--cp-text-muted); margin-bottom: 6px; }
.kpi-card .value { font-size: 2.1rem; font-weight: 800; color: var(--cp-link); line-height: 1; }
.kpi-card .sub { font-size: 0.8rem; color: var(--cp-text-soft); margin-top: 6px; }
.kpi-card.fabric-card { border-left: 4px solid var(--cp-success); }
.kpi-card.fabric-card .value { color: var(--cp-success); }
.kpi-card.warn-card { border-left: 4px solid var(--cp-warning); }
.kpi-card.warn-card .value { color: var(--cp-warning); }

.chart-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr)); gap: 20px; }
.chart-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; padding: 20px 24px 16px; box-shadow: var(--cp-shadow); }
.chart-card h3 { font-size: 0.85rem; font-weight: 600; color: var(--cp-text-muted); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 16px; }
.chart-card canvas { max-height: 260px; }

.fabric-banner { background: linear-gradient(135deg, var(--cp-accent-soft), rgba(22,163,74,0.07)); border: 1px solid var(--cp-border); border-left: 4px solid var(--cp-success); border-radius: 12px; padding: 20px 28px; display: flex; gap: 20px; align-items: flex-start; flex-wrap: wrap; }
.fabric-item { flex: 1; min-width: 140px; }
.fabric-item .fab-label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--cp-text-muted); }
.fabric-item .fab-value { font-size: 1.5rem; font-weight: 800; color: var(--cp-success); }
.fabric-item .fab-sub { font-size: 0.8rem; color: var(--cp-text-soft); margin-top: 2px; }

.table-wrap { overflow-x: auto; border-radius: 12px; border: 1px solid var(--cp-border); box-shadow: var(--cp-shadow); }
table { width: 100%; border-collapse: collapse; background: var(--cp-surface); }
thead th { background: var(--cp-surface-soft); color: var(--cp-text-muted); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; padding: 10px 16px; text-align: left; border-bottom: 1px solid var(--cp-border); white-space: nowrap; }
tbody tr { border-bottom: 1px solid var(--cp-border); transition: background 0.1s; }
tbody tr:last-child { border-bottom: none; }
tbody tr:hover { background: var(--cp-accent-soft); }
tbody td { padding: 9px 16px; font-size: 0.85rem; vertical-align: middle; }
.badge { display: inline-block; padding: 2px 10px; border-radius: 99px; font-size: 0.72rem; font-weight: 600; }
.badge-fabric  { background: rgba(22,163,74,0.12); color: var(--cp-success); }
.badge-premium { background: var(--cp-accent-soft); color: var(--cp-accent); }
.bar-cell { display: flex; align-items: center; gap: 8px; }
.mini-bar { height: 6px; border-radius: 3px; min-width: 2px; }

.findings-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; }
.finding-card { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 12px; padding: 18px 20px; box-shadow: var(--cp-shadow); }
.finding-card .f-icon { font-size: 1.5rem; margin-bottom: 8px; }
.finding-card h4 { font-size: 0.9rem; font-weight: 700; margin-bottom: 6px; }
.finding-card p { font-size: 0.82rem; color: var(--cp-text-soft); line-height: 1.55; }
.finding-card.rec  { border-left: 3px solid var(--cp-success); }
.finding-card.risk { border-left: 3px solid var(--cp-warning); }
.finding-card.info { border-left: 3px solid var(--cp-link); }

.report-footer { text-align: center; padding: 24px; font-size: 0.78rem; color: var(--cp-text-muted); border-top: 1px solid var(--cp-border); margin-top: 48px; }
.theme-toggle { position: fixed; top: 16px; right: 20px; background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 8px; padding: 6px 12px; cursor: pointer; font-size: 0.8rem; color: var(--cp-text-muted); z-index: 100; box-shadow: var(--cp-shadow); }
.theme-toggle:hover { background: var(--cp-surface-soft); }
</style>
</head>
<body>

<button class="theme-toggle" onclick="toggleTheme()">$($T.themeBtn)</button>

<header class="report-header">
  <div>
    <div style="font-size:0.8rem;opacity:0.75;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:4px"><a href="https://github.com/pjunco/PBI-Assessment" target="_blank" style="color:inherit;text-decoration:none;opacity:0.9;">$($T.headerLabel)</a></div>
    <h1>$CustomerName – Executive Report</h1>
    <div class="subtitle">$($T.headerSubtitle)</div>
  </div>
  <div class="meta">
    <div>$($T.headerDate) $reportDate</div>
    <div style="margin-top:4px">$($T.headerBy)</div>
  </div>
</header>

<div class="container">

  <div class="section-title"><span>📊</span> $($T.secOverview)</div>
  <div class="kpi-grid" id="kpiGrid"></div>

  <div class="section-title"><span>🟢</span> $($T.secFabric)</div>
  <div class="fabric-banner">
    <div class="fabric-item">
      <div class="fab-label">$($T.fabCapLabel)</div>
      <div class="fab-value">$fabricWS</div>
      <div class="fab-sub">workspaces ($([math]::Round($fabricWS / [math]::Max($totalWS,1) * 100, 1))$($T.fabOfTotal))</div>
    </div>
    <div class="fabric-item">
      <div class="fab-label">$($T.fabSKULabel)</div>
      <div class="fab-value">$fabricSku</div>
      <div class="fab-sub">$($T.fabCapName) $fabricCap</div>
    </div>
    <div class="fabric-item">
      <div class="fab-label">$($T.fabWSLabel)</div>
      <div class="fab-value" style="font-size:0.9rem;margin-top:6px">$fabricNames</div>
      <div class="fab-sub">$(if ($fabricWS -eq 0) { $T.fabNone } elseif ($fabricWS -le 3) { $T.fabPilot } else { $T.fabExpanding })</div>
    </div>
    <div class="fabric-item">
      <div class="fab-label">$($T.fabLSMLabel)</div>
      <div class="fab-value" style="font-size:0.9rem;margin-top:6px">$(if ($lsmEnabled -gt 0) { "$lsmEnabled $($T.fabLSMEnabled)" } else { $T.fabLSMNone })</div>
      <div class="fab-sub">$lsmText</div>
    </div>
  </div>

  <div class="section-title"><span>📈</span> $($T.secCapacity)</div>
  <div class="chart-grid">
    <div class="chart-card"><h3>$($T.chartSKU)</h3><canvas id="skuChart"></canvas></div>
    <div class="chart-card"><h3>$($T.chartConn)</h3><canvas id="connChart"></canvas></div>
    <div class="chart-card"><h3>$($T.chartCap)</h3><canvas id="capChart"></canvas></div>
  </div>

  <div class="section-title"><span>🗄️</span> $($T.secDS)</div>
  <div class="chart-grid">
    <div class="chart-card" style="grid-column:span 2"><h3>$($T.chartDS)</h3><canvas id="dsChart" style="max-height:300px"></canvas></div>
    <div class="chart-card"><h3>$($T.chartTopWS)</h3><canvas id="topWsChart" style="max-height:340px"></canvas></div>
  </div>

  <div class="section-title"><span>📋</span> $($T.secWS)</div>
  <div class="table-wrap">
    <table>
      <thead><tr><th>$($T.tblNum)</th><th>$($T.tblWS)</th><th>$($T.tblType)</th><th>$($T.tblCap)</th><th>$($T.tblSKU)</th><th>$($T.tblReports)</th><th>$($T.tblStorage)</th></tr></thead>
      <tbody id="wsTableBody"></tbody>
    </table>
  </div>

  <div class="section-title"><span>💡</span> $($T.secFindings)</div>
  <div class="findings-grid" id="findingsGrid"></div>

</div>

<div class="report-footer">
  $CustomerName &nbsp;·&nbsp; Power BI Assessment &nbsp;·&nbsp; $($T.footerOn) $reportDate &nbsp;·&nbsp; Microsoft Copilot &amp; GitHub Copilot
</div>

<script>
// ── EMBEDDED DATA ──────────────────────────────────────────────────────────
const DATA = {
  totalWS:      $totalWS,
  fabricWS:     $fabricWS,
  premiumWS:    $premiumWS,
  emptyWS:      $emptyWS,
  totalReports: $totalReports,
  importR:      $importR,
  dqR:          $dqR,
  unkR:         $unkR,
  importPct:    $importPct,
  dqPct:        $dqPct,
  skuLabels:  [$skuLabels],
  skuData:    [$skuData],
  skuNames:   [$skuNames],
  capLabels:  [$capLabels],
  capData:    [$capData],
  dsLabels:   [$dsLabels],
  dsData:     [$dsData],
  top10Labels:[$top10Labels],
  top10Data:  [$top10Data],
  top10Colors:[$top10Colors],
  workspaces: [
    $wsJsonRows
  ]
};

// ── TRANSLATIONS ────────────────────────────────────────────────────────────
const T = {
  kpiWSLabel:      '$($T.kpiWSLabel)',
  kpiWSSub:        '$($T.kpiWSSub)',
  kpiRepLabel:     '$($T.kpiRepLabel)',
  kpiRepSub:       '$($T.kpiRepSub)',
  kpiImpLabel:     '$($T.kpiImpLabel)',
  kpiRepWord:      '$($T.kpiRepWord)',
  kpiDQLabel:      '$($T.kpiDQLabel)',
  kpiEmptyLabel:   '$($T.kpiEmptyLabel)',
  kpiEmptySub:     '$($T.kpiEmptySub)',
  kpiFabLabel:     '$($T.kpiFabLabel)',
  kpiFabSub:       '$($T.kpiFabSub)',
  connImport:      '$($T.connImport)',
  connDQ:          '$($T.connDQ)',
  connUnk:         '$($T.connUnk)',
  connLabel:       '$($T.connLabel)',
  fImpHighTitle:   '$($T.fImpHighTitle)',
  fImpHighText:    '$($T.fImpHighText)',
  fDQHighTitle:    '$($T.fDQHighTitle)',
  fDQHighText:     '$($T.fDQHighText)',
  fFab0Title:      '$($T.fFab0Title)',
  fFab0Text:       '$($T.fFab0Text)',
  fFabPilotTitle:  '$($T.fFabPilotTitle)',
  fFabPilotText:   '$($T.fFabPilotText)',
  fFabGoodTitle:   '$($T.fFabGoodTitle)',
  fFabGoodText:    '$($T.fFabGoodText)',
  fEmptyTitle:     '$($T.fEmptyTitle)',
  fEmptyText:      '$($T.fEmptyText)',
  fLSMTitle:       '$($T.fLSMTitle)',
  fLSMEnabledText: '$($T.fLSMEnabledText)',
  fLSMDisabledText:'$($T.fLSMDisabledText)',
  fODBCTitle:      '$($T.fODBCTitle)',
  fODBCText:       '$($T.fODBCText)',
  fFileTitle:      '$($T.fFileTitle)',
  fFileText:       '$($T.fFileText)',
  fTop3Title:      '$($T.fTop3Title)',
  fTop3Of:         '$($T.fTop3Of)',
  fTop3Sum:        '$($T.fTop3Sum)',
  wsAnd:           '$($T.wsAnd)',
  themeBtnBlue:    '$($T.themeBtnBlue)',
  themeBtnRed:     '$($T.themeBtnRed)',
};

// ── KPI CARDS ───────────────────────────────────────────────────────────────
const kpis = [
  { label: T.kpiWSLabel,    value: DATA.totalWS,                        sub: T.kpiWSSub,                                                          cls: '' },
  { label: T.kpiRepLabel,   value: DATA.totalReports.toLocaleString(),   sub: T.kpiRepSub,                                                         cls: '' },
  { label: T.kpiImpLabel,   value: DATA.importPct + '%',                 sub: DATA.importR + ' ' + T.kpiRepWord,                                   cls: '' },
  { label: T.kpiDQLabel,    value: DATA.dqPct + '%',                     sub: DATA.dqR + ' ' + T.kpiRepWord,                                       cls: 'warn-card' },
  { label: T.kpiEmptyLabel, value: DATA.emptyWS,                         sub: (Math.round(DATA.emptyWS/Math.max(DATA.totalWS,1)*1000)/10) + T.kpiEmptySub, cls: 'warn-card' },
  { label: T.kpiFabLabel,   value: DATA.fabricWS,                        sub: T.kpiFabSub,                                                         cls: 'fabric-card' },
];
const kpiGrid = document.getElementById('kpiGrid');
kpis.forEach(k => {
  kpiGrid.innerHTML += '<div class="kpi-card ' + k.cls + '"><div class="label">' + k.label + '</div><div class="value">' + k.value + '</div><div class="sub">' + k.sub + '</div></div>';
});

// ── WORKSPACE TABLE ─────────────────────────────────────────────────────────
const tbody = document.getElementById('wsTableBody');
const maxR = Math.max(...DATA.workspaces.map(w => w.reports), 1);
DATA.workspaces.forEach((w, i) => {
  const isFabric = w.type === 'Fabric Capacity';
  const barW = Math.round(w.reports / maxR * 80);
  const barColor = isFabric ? '#16a34a' : '#b11f4b';
  const skuColor = { P2:'#b11f4b', P1:'#0078d4', PP3:'#f59e0b', F8:'#16a34a', A1:'#8b5cf6' }[w.sku] || '#919191';
  tbody.innerHTML += '<tr>' +
    '<td style="color:var(--cp-text-muted)">' + (i+1) + '</td>' +
    '<td><strong>' + w.name + '</strong></td>' +
    '<td><span class="badge ' + (isFabric?'badge-fabric':'badge-premium') + '">' + (isFabric?'\ud83d\udfe2 Fabric':'\ud83d\udd35 Premium') + '</span></td>' +
    '<td style="color:var(--cp-text-soft);font-size:0.8rem">' + w.cap + '</td>' +
    '<td style="color:' + skuColor + ';font-weight:700">' + w.sku + '</td>' +
    '<td><div class="bar-cell"><div class="mini-bar" style="width:' + barW + 'px;background:' + barColor + '"></div><span>' + w.reports + '</span></div></td>' +
    '<td style="color:var(--cp-text-soft)">' + w.storage + '</td>' +
    '</tr>';
});

// ── FINDINGS ────────────────────────────────────────────────────────────────
const findings = [];

// Import mode
if (DATA.importPct >= 90) {
  findings.push({ cls:'rec', icon:'📦', title: T.fImpHighTitle + ' (' + DATA.importPct + '%)', text: T.fImpHighText });
} else if (DATA.dqPct >= 20) {
  findings.push({ cls:'info', icon:'⚡', title: T.fDQHighTitle + ' (' + DATA.dqPct + '%)', text: T.fDQHighText.replace('PCTX', DATA.dqPct) });
}

// Fabric adoption
if (DATA.fabricWS === 0) {
  findings.push({ cls:'risk', icon:'⚠️', title: T.fFab0Title, text: T.fFab0Text });
} else if (DATA.fabricWS <= 3) {
  findings.push({ cls:'rec', icon:'🟢', title: T.fFabPilotTitle + ' (' + DATA.fabricWS + ' workspace' + (DATA.fabricWS>1?'s':'') + ')', text: T.fFabPilotText });
} else {
  findings.push({ cls:'rec', icon:'🚀', title: T.fFabGoodTitle + ' (' + DATA.fabricWS + ' workspaces)', text: T.fFabGoodText });
}

// Empty workspaces
if (DATA.emptyWS > 0) {
  findings.push({ cls:'risk', icon:'⚠️',
    title: DATA.emptyWS + ' ' + T.fEmptyTitle,
    text: Math.round(DATA.emptyWS/Math.max(DATA.totalWS,1)*100) + T.fEmptyText });
}

// LSM
findings.push({ cls:'info', icon:'🗃️', title: T.fLSMTitle,
  text: DATA.workspaces.filter(w=>w.storage==='Large').length > 0 ? T.fLSMEnabledText : T.fLSMDisabledText });

// Data sources
const hasODBC    = DATA.dsLabels.includes('ODBC');
const hasOracle  = DATA.dsLabels.includes('Oracle');
const hasFileWeb = DATA.dsLabels.includes('File') || DATA.dsLabels.includes('Web') || DATA.dsLabels.includes('Folder');
if (hasODBC || hasOracle) {
  findings.push({ cls:'info', icon:'🔌', title: T.fODBCTitle, text: T.fODBCText });
}
if (hasFileWeb) {
  findings.push({ cls:'risk', icon:'📂', title: T.fFileTitle, text: T.fFileText });
}

// Top workspace concentration
const top3Reports = DATA.workspaces.slice(0,3).reduce((a,w)=>a+w.reports,0);
const top3Pct = DATA.totalReports>0 ? Math.round(top3Reports/DATA.totalReports*100) : 0;
if (top3Pct > 30) {
  findings.push({ cls:'info', icon:'🏆',
    title: T.fTop3Title + ' ' + top3Pct + T.fTop3Of,
    text: (DATA.workspaces[0]?.name||'') + ', ' + (DATA.workspaces[1]?.name||'') + ' ' + T.wsAnd + ' ' + (DATA.workspaces[2]?.name||'') + ' — ' + T.fTop3Sum.replace('REPSX', top3Reports) });
}

const fg = document.getElementById('findingsGrid');
findings.forEach(f => {
  fg.innerHTML += '<div class="finding-card ' + f.cls + '"><div class="f-icon">' + f.icon + '</div><h4>' + f.title + '</h4><p>' + f.text + '</p></div>';
});

// ── CHARTS ──────────────────────────────────────────────────────────────────
const PALETTE = ['#b11f4b','#0078d4','#f59e0b','#16a34a','#8b5cf6','#ec4899','#f97316','#14b8a6','#64748b','#e11d48'];

new Chart(document.getElementById('skuChart'), {
  type: 'doughnut',
  data: { labels: DATA.skuLabels, datasets: [{ data: DATA.skuData, backgroundColor: PALETTE, borderWidth: 2, borderColor: 'var(--cp-surface)' }] },
  options: { plugins: { legend: { position:'bottom', labels: { color:'var(--cp-text)', font:{size:11} } } }, cutout:'62%' }
});

new Chart(document.getElementById('connChart'), {
  type: 'doughnut',
  data: {
    labels: [T.connImport + ' (' + DATA.importR + ')', T.connDQ + ' (' + DATA.dqR + ')', T.connUnk + ' (' + DATA.unkR + ')'],
    datasets: [{ data: [DATA.importR, DATA.dqR, DATA.unkR], backgroundColor: ['#b11f4b','#f59e0b','#919191'], borderWidth: 2, borderColor: 'var(--cp-surface)' }]
  },
  options: { plugins: { legend: { position:'bottom', labels: { color:'var(--cp-text)', font:{size:11} } } }, cutout:'62%' }
});

new Chart(document.getElementById('capChart'), {
  type: 'bar',
  data: { labels: DATA.capLabels, datasets: [{ label:'Workspaces', data: DATA.capData, backgroundColor: PALETTE, borderRadius: 6 }] },
  options: { indexAxis:'y', plugins:{ legend:{display:false} }, scales: { x:{ticks:{color:'var(--cp-text-muted)'},grid:{color:'var(--cp-border)'}}, y:{ticks:{color:'var(--cp-text)',font:{size:11}},grid:{display:false}} } }
});

new Chart(document.getElementById('dsChart'), {
  type: 'bar',
  data: { labels: DATA.dsLabels, datasets: [{ label: T.connLabel, data: DATA.dsData, backgroundColor: PALETTE, borderRadius: 6 }] },
  options: { plugins:{ legend:{display:false} }, scales: { x:{ticks:{color:'var(--cp-text-muted)'},grid:{color:'var(--cp-border)'}}, y:{ticks:{color:'var(--cp-text)'},grid:{color:'var(--cp-border)'}} } }
});

new Chart(document.getElementById('topWsChart'), {
  type: 'bar',
  data: { labels: DATA.top10Labels, datasets: [{ label: T.kpiRepLabel, data: DATA.top10Data, backgroundColor: DATA.top10Colors, borderRadius: 6 }] },
  options: { indexAxis:'y', plugins:{ legend:{display:false} }, scales: { x:{ticks:{color:'var(--cp-text-muted)'},grid:{color:'var(--cp-border)'}}, y:{ticks:{color:'var(--cp-text)',font:{size:11}},grid:{display:false}} } }
});

function toggleTheme() {
  const cur = document.documentElement.getAttribute('data-theme');
  const next = cur === 'red' ? 'blue' : 'red';
  document.documentElement.setAttribute('data-theme', next);
  document.querySelector('.theme-toggle').textContent = next === 'red' ? T.themeBtnBlue : T.themeBtnRed;
}
</script>
</body>
</html>
"@

# ── 4. Write file ─────────────────────────────────────────────────────────────
[System.IO.File]::WriteAllText($ReportPath, $html, [System.Text.UTF8Encoding]::new($false))
Write-Host ""
Write-Host "Report saved to: $ReportPath" -ForegroundColor Green
Write-Host ""

# Open in default browser
try { Start-Process $ReportPath } catch {}
